package server

import (
 "context"
 pb "github.com/mikhmon/mikrotik-go-service/proto"
)

func (s *RouterServiceServer) GetDashboard(ctx context.Context, req *pb.GetDashboardRequest) (*pb.GetDashboardResponse,error) { r:=&pb.GetDashboardResponse{}; c,e:=s.dial(ctx,req.SessionId); if e!=nil{r.Error=e.Error();return r,nil}; defer c.Close(); id,e:=c.Run("/system/identity/print");if e!=nil{r.Error=e.Error();return r,nil}; rs,e:=c.Run("/system/resource/print");if e!=nil{r.Error=e.Error();return r,nil};if len(id)>0{r.Identity=id[0]["name"]};if len(rs)>0{x:=rs[0];r.Version=x["version"];r.RosVersion=x["version"];r.Uptime=x["uptime"];r.CpuLoad=x["cpu-load"];r.FreeMemory=x["free-memory"];r.TotalMemory=x["total-memory"];r.FreeHdd=x["free-hdd-space"];r.TotalHdd=x["total-hdd-space"]};if a,e:=c.Run("/ip/hotspot/active/print");e==nil{r.ActiveHotspotUsers=int32(len(a))};if u,e:=c.Run("/ip/hotspot/user/print");e==nil{r.TotalHotspotUsers=int32(len(u))};r.Success=true;return r,nil }
func (s *RouterServiceServer) ListActiveHotspotUsers(ctx context.Context, req *pb.ListActiveRequest) (*pb.ListActiveResponse,error) { r:=&pb.ListActiveResponse{};c,e:=s.dial(ctx,req.SessionId);if e!=nil{r.Error=e.Error();return r,nil};defer c.Close();w:=[]string{};if req.Server!=""{w=append(w,"?server="+req.Server)};rows,e:=c.Run("/ip/hotspot/active/print",w...);if e!=nil{r.Error=e.Error();return r,nil};for _,x:=range rows{r.Users=append(r.Users,&pb.ActiveHotspotUser{Id:x[".id"],User:x["user"],Address:x["address"],MacAddress:x["mac-address"],Uptime:x["uptime"],BytesIn:x["bytes-in"],BytesOut:x["bytes-out"],PacketsIn:x["packets-in"],PacketsOut:x["packets-out"],Server:x["server"]})};r.Success=true;return r,nil }
func (s *RouterServiceServer) GetInterfaces(ctx context.Context, req *pb.InterfacesRequest) (*pb.InterfacesResponse,error) { r:=&pb.InterfacesResponse{};c,e:=s.dial(ctx,req.SessionId);if e!=nil{r.Error=e.Error();return r,nil};defer c.Close();rows,e:=c.Run("/interface/print");if e!=nil{r.Error=e.Error();return r,nil};for _,x:=range rows{tx:=x["tx-byte"];if tx==""{tx=x["tx"]};rx:=x["rx-byte"];if rx==""{rx=x["rx"]};r.Interfaces=append(r.Interfaces,&pb.InterfaceInfo{Id:x[".id"],Name:x["name"],Type:x["type"],MacAddress:x["mac-address"],Tx:tx,Rx:rx,Running:x["running"]})};r.Success=true;return r,nil }
func (s *RouterServiceServer) ListPppSecrets(ctx context.Context, req *pb.ListPppSecretsRequest) (*pb.ListPppSecretsResponse,error) { r:=&pb.ListPppSecretsResponse{};c,e:=s.dial(ctx,req.SessionId);if e!=nil{r.Error=e.Error();return r,nil};defer c.Close();w:=[]string{};if req.Profile!=""{w=append(w,"?profile="+req.Profile)};if req.Name!=""{w=append(w,"?name="+req.Name)};rows,e:=c.Run("/ppp/secret/print",w...);if e!=nil{r.Error=e.Error();return r,nil};for _,x:=range rows{r.Secrets=append(r.Secrets,&pb.PppSecret{Id:x[".id"],Name:x["name"],Password:x["password"],Service:x["service"],Profile:x["profile"],LocalAddress:x["local-address"],RemoteAddress:x["remote-address"],Comment:x["comment"],Disabled:x["disabled"]})};r.Success=true;return r,nil }
