package server

import (
    "context"
    "strings"
    pb "github.com/mikhmon/mikrotik-go-service/proto"
    "github.com/mikhmon/mikrotik-go-service/internal/store"
)

func toSessionInfo(rs *store.RouterSession) *pb.RouterSessionInfo { return &pb.RouterSessionInfo{Id:rs.ID,Name:rs.Name,Ip:rs.IP,Port:int32(rs.Port),User:rs.User,HotspotName:rs.HotspotName,DnsName:rs.DNSName,Currency:rs.Currency,ReloadInterval:int32(rs.ReloadInterval),Iface:rs.Iface,IdleTo:int32(rs.IdleTo),Livereport:rs.Livereport} }
func (s *RouterServiceServer) ListSessions(ctx context.Context, req *pb.ListSessionsRequest)(*pb.ListSessionsResponse,error){rows,err:=s.store.List(ctx);if err!=nil{return &pb.ListSessionsResponse{Error:err.Error()},nil};r:=&pb.ListSessionsResponse{Success:true};for i:=range rows{r.Sessions=append(r.Sessions,toSessionInfo(&rows[i]))};return r,nil}
func (s *RouterServiceServer) GetSession(ctx context.Context, req *pb.GetSessionRequest)(*pb.GetSessionResponse,error){if strings.TrimSpace(req.Id)==""{return &pb.GetSessionResponse{Error:"id wajib diisi"},nil};rs,err:=s.store.Get(ctx,req.Id);if err!=nil{return &pb.GetSessionResponse{Error:"router session tidak ditemukan"},nil};return &pb.GetSessionResponse{Success:true,Session:toSessionInfo(rs)},nil}
func (s *RouterServiceServer) CreateSession(ctx context.Context, req *pb.CreateSessionRequest)(*pb.CreateSessionResponse,error){if strings.TrimSpace(req.Id)==""||strings.TrimSpace(req.Name)==""||strings.TrimSpace(req.Ip)==""||strings.TrimSpace(req.Password)==""{return &pb.CreateSessionResponse{Error:"id, name, ip, dan password wajib diisi"},nil};if ok,e:=s.store.Exists(ctx,req.Id);e!=nil{return &pb.CreateSessionResponse{Error:e.Error()},nil}else if ok{return &pb.CreateSessionResponse{Error:"session id sudah digunakan"},nil};port:=int(req.Port);if port==0{port=8728};rs:=store.RouterSession{ID:req.Id,Name:req.Name,IP:req.Ip,Port:port,User:req.User,Password:req.Password,HotspotName:req.HotspotName,DNSName:req.DnsName,Currency:req.Currency,ReloadInterval:int(req.ReloadInterval),Iface:req.Iface,IdleTo:int(req.IdleTo),Livereport:req.Livereport};if err:=s.store.Create(ctx,rs);err!=nil{return &pb.CreateSessionResponse{Error:err.Error()},nil};return &pb.CreateSessionResponse{Success:true,Session:toSessionInfo(&rs)},nil}
func (s *RouterServiceServer) UpdateSession(ctx context.Context, req *pb.UpdateSessionRequest)(*pb.UpdateSessionResponse,error){if strings.TrimSpace(req.Id)==""{return &pb.UpdateSessionResponse{Error:"id wajib diisi"},nil};port:=int(req.Port);if port==0{port=8728};rs:=store.RouterSession{ID:req.Id,Name:req.Name,IP:req.Ip,Port:port,User:req.User,Password:req.Password,HotspotName:req.HotspotName,DNSName:req.DnsName,Currency:req.Currency,ReloadInterval:int(req.ReloadInterval),Iface:req.Iface,IdleTo:int(req.IdleTo),Livereport:req.Livereport};ok,err:=s.store.Update(ctx,rs);if err!=nil{return &pb.UpdateSessionResponse{Error:err.Error()},nil};if !ok{return &pb.UpdateSessionResponse{Error:"router session tidak ditemukan"},nil};return &pb.UpdateSessionResponse{Success:true,Session:toSessionInfo(&rs)},nil}
func (s *RouterServiceServer) DeleteSession(ctx context.Context, req *pb.DeleteSessionRequest)(*pb.DeleteSessionResponse,error){if strings.TrimSpace(req.Id)==""{return &pb.DeleteSessionResponse{Error:"id wajib diisi"},nil};ok,err:=s.store.Delete(ctx,req.Id);if err!=nil{return &pb.DeleteSessionResponse{Error:err.Error()},nil};if !ok{return &pb.DeleteSessionResponse{Error:"router session tidak ditemukan"},nil};return &pb.DeleteSessionResponse{Success:true},nil}
