// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// RouterServiceClient is the client API for RouterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouterServiceClient interface {
	// Connection test
	TestConnect(ctx context.Context, in *TestConnectRequest, opts ...grpc.CallOption) (*TestConnectResponse, error)
	// Dashboard
	GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardResponse, error)
	// Hotspot users
	ListActiveHotspotUsers(ctx context.Context, in *ListActiveRequest, opts ...grpc.CallOption) (*ListActiveResponse, error)
	ListHotspotUsers(ctx context.Context, in *ListHotspotUsersRequest, opts ...grpc.CallOption) (*ListHotspotUsersResponse, error)
	AddHotspotUser(ctx context.Context, in *AddHotspotUserRequest, opts ...grpc.CallOption) (*AddHotspotUserResponse, error)
	RemoveHotspotUser(ctx context.Context, in *RemoveHotspotUserRequest, opts ...grpc.CallOption) (*RemoveHotspotUserResponse, error)
	// Suspend/restore a hotspot customer without deleting their account —
	// mirrors DisablePppSecret/EnablePppSecret below. Needed by
	// payment-service's billing overdue-suspension flow (billing customers
	// whose `type` is 'hotspot' rather than 'pppoe').
	DisableHotspotUser(ctx context.Context, in *DisableHotspotUserRequest, opts ...grpc.CallOption) (*DisableHotspotUserResponse, error)
	EnableHotspotUser(ctx context.Context, in *EnableHotspotUserRequest, opts ...grpc.CallOption) (*EnableHotspotUserResponse, error)
	// Hotspot profiles
	ListHotspotProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error)
	GetHotspotProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	// Generic field-passthrough CRUD, mirroring AddPppProfile/UpdatePppProfile/
	// DeletePppProfile below — Go doesn't understand MikHMon's on-login script
	// metadata (price/validity/expiry mode encoded into the script text), it
	// just writes whatever `on_login` string the caller built. That business
	// logic lives in erp-node-service (ported from the monolith's
	// buildOnLoginScript/parseOnLogin), not here — same "smart client, dumb
	// server" split used for router-session management.
	AddHotspotProfile(ctx context.Context, in *AddHotspotProfileRequest, opts ...grpc.CallOption) (*AddHotspotProfileResponse, error)
	UpdateHotspotProfile(ctx context.Context, in *UpdateHotspotProfileRequest, opts ...grpc.CallOption) (*UpdateHotspotProfileResponse, error)
	DeleteHotspotProfile(ctx context.Context, in *DeleteHotspotProfileRequest, opts ...grpc.CallOption) (*DeleteHotspotProfileResponse, error)
	// Bulk-remove — just RemoveHotspotUser looped server-side so the caller
	// makes one round-trip instead of N.
	BulkRemoveHotspotUsers(ctx context.Context, in *BulkRemoveHotspotUsersRequest, opts ...grpc.CallOption) (*BulkRemoveHotspotUsersResponse, error)
	// Idempotent: creates the "mikhmon-cleanup-expired" scheduler if missing,
	// otherwise just re-confirms it (used after every profile save, matching
	// the monolith calling this on every add/edit). The cleanup script itself
	// is fixed/static (no customer input), so it's hardcoded here rather than
	// sent over the wire from erp-node-service.
	SetupExpiryScheduler(ctx context.Context, in *SetupExpirySchedulerRequest, opts ...grpc.CallOption) (*SetupExpirySchedulerResponse, error)
	// System info
	GetSystemResource(ctx context.Context, in *SystemResourceRequest, opts ...grpc.CallOption) (*SystemResourceResponse, error)
	GetInterfaces(ctx context.Context, in *InterfacesRequest, opts ...grpc.CallOption) (*InterfacesResponse, error)
	// Router session management (CRUD) — the router connection profiles
	// (id, ip, credentials, hotspot/UI settings) that every other RPC above
	// is dialed against via session_id.
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*UpdateSessionResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	// ── PPPoE secrets ────────────────────────────────────────────────
	ListPppSecrets(ctx context.Context, in *ListPppSecretsRequest, opts ...grpc.CallOption) (*ListPppSecretsResponse, error)
	GetPppSecret(ctx context.Context, in *GetPppSecretRequest, opts ...grpc.CallOption) (*GetPppSecretResponse, error)
	AddPppSecret(ctx context.Context, in *AddPppSecretRequest, opts ...grpc.CallOption) (*AddPppSecretResponse, error)
	UpdatePppSecret(ctx context.Context, in *UpdatePppSecretRequest, opts ...grpc.CallOption) (*UpdatePppSecretResponse, error)
	DeletePppSecret(ctx context.Context, in *DeletePppSecretRequest, opts ...grpc.CallOption) (*DeletePppSecretResponse, error)
	EnablePppSecret(ctx context.Context, in *EnablePppSecretRequest, opts ...grpc.CallOption) (*EnablePppSecretResponse, error)
	DisablePppSecret(ctx context.Context, in *DisablePppSecretRequest, opts ...grpc.CallOption) (*DisablePppSecretResponse, error)
	// ── PPPoE profiles ───────────────────────────────────────────────
	ListPppProfiles(ctx context.Context, in *ListPppProfilesRequest, opts ...grpc.CallOption) (*ListPppProfilesResponse, error)
	AddPppProfile(ctx context.Context, in *AddPppProfileRequest, opts ...grpc.CallOption) (*AddPppProfileResponse, error)
	UpdatePppProfile(ctx context.Context, in *UpdatePppProfileRequest, opts ...grpc.CallOption) (*UpdatePppProfileResponse, error)
	DeletePppProfile(ctx context.Context, in *DeletePppProfileRequest, opts ...grpc.CallOption) (*DeletePppProfileResponse, error)
	// ── PPPoE active conns & pools ───────────────────────────────────
	ListPppActive(ctx context.Context, in *ListPppActiveRequest, opts ...grpc.CallOption) (*ListPppActiveResponse, error)
	DisconnectPppActive(ctx context.Context, in *DisconnectPppActiveRequest, opts ...grpc.CallOption) (*DisconnectPppActiveResponse, error)
	ListPppPools(ctx context.Context, in *ListPppPoolsRequest, opts ...grpc.CallOption) (*ListPppPoolsResponse, error)
}

type routerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterServiceClient(cc grpc.ClientConnInterface) RouterServiceClient {
	return &routerServiceClient{cc}
}

func (c *routerServiceClient) TestConnect(ctx context.Context, in *TestConnectRequest, opts ...grpc.CallOption) (*TestConnectResponse, error) {
	out := new(TestConnectResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/TestConnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardResponse, error) {
	out := new(GetDashboardResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/GetDashboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListActiveHotspotUsers(ctx context.Context, in *ListActiveRequest, opts ...grpc.CallOption) (*ListActiveResponse, error) {
	out := new(ListActiveResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/ListActiveHotspotUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListHotspotUsers(ctx context.Context, in *ListHotspotUsersRequest, opts ...grpc.CallOption) (*ListHotspotUsersResponse, error) {
	out := new(ListHotspotUsersResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/ListHotspotUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) AddHotspotUser(ctx context.Context, in *AddHotspotUserRequest, opts ...grpc.CallOption) (*AddHotspotUserResponse, error) {
	out := new(AddHotspotUserResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/AddHotspotUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) RemoveHotspotUser(ctx context.Context, in *RemoveHotspotUserRequest, opts ...grpc.CallOption) (*RemoveHotspotUserResponse, error) {
	out := new(RemoveHotspotUserResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/RemoveHotspotUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) DisableHotspotUser(ctx context.Context, in *DisableHotspotUserRequest, opts ...grpc.CallOption) (*DisableHotspotUserResponse, error) {
	out := new(DisableHotspotUserResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/DisableHotspotUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) EnableHotspotUser(ctx context.Context, in *EnableHotspotUserRequest, opts ...grpc.CallOption) (*EnableHotspotUserResponse, error) {
	out := new(EnableHotspotUserResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/EnableHotspotUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListHotspotProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/ListHotspotProfiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetHotspotProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/GetHotspotProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) AddHotspotProfile(ctx context.Context, in *AddHotspotProfileRequest, opts ...grpc.CallOption) (*AddHotspotProfileResponse, error) {
	out := new(AddHotspotProfileResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/AddHotspotProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) UpdateHotspotProfile(ctx context.Context, in *UpdateHotspotProfileRequest, opts ...grpc.CallOption) (*UpdateHotspotProfileResponse, error) {
	out := new(UpdateHotspotProfileResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/UpdateHotspotProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) DeleteHotspotProfile(ctx context.Context, in *DeleteHotspotProfileRequest, opts ...grpc.CallOption) (*DeleteHotspotProfileResponse, error) {
	out := new(DeleteHotspotProfileResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/DeleteHotspotProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) BulkRemoveHotspotUsers(ctx context.Context, in *BulkRemoveHotspotUsersRequest, opts ...grpc.CallOption) (*BulkRemoveHotspotUsersResponse, error) {
	out := new(BulkRemoveHotspotUsersResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/BulkRemoveHotspotUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) SetupExpiryScheduler(ctx context.Context, in *SetupExpirySchedulerRequest, opts ...grpc.CallOption) (*SetupExpirySchedulerResponse, error) {
	out := new(SetupExpirySchedulerResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/SetupExpiryScheduler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetSystemResource(ctx context.Context, in *SystemResourceRequest, opts ...grpc.CallOption) (*SystemResourceResponse, error) {
	out := new(SystemResourceResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/GetSystemResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetInterfaces(ctx context.Context, in *InterfacesRequest, opts ...grpc.CallOption) (*InterfacesResponse, error) {
	out := new(InterfacesResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/GetInterfaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/ListSessions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/GetSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/CreateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*UpdateSessionResponse, error) {
	out := new(UpdateSessionResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/UpdateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/DeleteSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListPppSecrets(ctx context.Context, in *ListPppSecretsRequest, opts ...grpc.CallOption) (*ListPppSecretsResponse, error) {
	out := new(ListPppSecretsResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/ListPppSecrets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetPppSecret(ctx context.Context, in *GetPppSecretRequest, opts ...grpc.CallOption) (*GetPppSecretResponse, error) {
	out := new(GetPppSecretResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/GetPppSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) AddPppSecret(ctx context.Context, in *AddPppSecretRequest, opts ...grpc.CallOption) (*AddPppSecretResponse, error) {
	out := new(AddPppSecretResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/AddPppSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) UpdatePppSecret(ctx context.Context, in *UpdatePppSecretRequest, opts ...grpc.CallOption) (*UpdatePppSecretResponse, error) {
	out := new(UpdatePppSecretResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/UpdatePppSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) DeletePppSecret(ctx context.Context, in *DeletePppSecretRequest, opts ...grpc.CallOption) (*DeletePppSecretResponse, error) {
	out := new(DeletePppSecretResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/DeletePppSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) EnablePppSecret(ctx context.Context, in *EnablePppSecretRequest, opts ...grpc.CallOption) (*EnablePppSecretResponse, error) {
	out := new(EnablePppSecretResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/EnablePppSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) DisablePppSecret(ctx context.Context, in *DisablePppSecretRequest, opts ...grpc.CallOption) (*DisablePppSecretResponse, error) {
	out := new(DisablePppSecretResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/DisablePppSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListPppProfiles(ctx context.Context, in *ListPppProfilesRequest, opts ...grpc.CallOption) (*ListPppProfilesResponse, error) {
	out := new(ListPppProfilesResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/ListPppProfiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) AddPppProfile(ctx context.Context, in *AddPppProfileRequest, opts ...grpc.CallOption) (*AddPppProfileResponse, error) {
	out := new(AddPppProfileResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/AddPppProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) UpdatePppProfile(ctx context.Context, in *UpdatePppProfileRequest, opts ...grpc.CallOption) (*UpdatePppProfileResponse, error) {
	out := new(UpdatePppProfileResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/UpdatePppProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) DeletePppProfile(ctx context.Context, in *DeletePppProfileRequest, opts ...grpc.CallOption) (*DeletePppProfileResponse, error) {
	out := new(DeletePppProfileResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/DeletePppProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListPppActive(ctx context.Context, in *ListPppActiveRequest, opts ...grpc.CallOption) (*ListPppActiveResponse, error) {
	out := new(ListPppActiveResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/ListPppActive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) DisconnectPppActive(ctx context.Context, in *DisconnectPppActiveRequest, opts ...grpc.CallOption) (*DisconnectPppActiveResponse, error) {
	out := new(DisconnectPppActiveResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/DisconnectPppActive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListPppPools(ctx context.Context, in *ListPppPoolsRequest, opts ...grpc.CallOption) (*ListPppPoolsResponse, error) {
	out := new(ListPppPoolsResponse)
	err := c.cc.Invoke(ctx, "/router.RouterService/ListPppPools", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServiceServer is the server API for RouterService service.
// All implementations must embed UnimplementedRouterServiceServer
// for forward compatibility
type RouterServiceServer interface {
	// Connection test
	TestConnect(context.Context, *TestConnectRequest) (*TestConnectResponse, error)
	// Dashboard
	GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardResponse, error)
	// Hotspot users
	ListActiveHotspotUsers(context.Context, *ListActiveRequest) (*ListActiveResponse, error)
	ListHotspotUsers(context.Context, *ListHotspotUsersRequest) (*ListHotspotUsersResponse, error)
	AddHotspotUser(context.Context, *AddHotspotUserRequest) (*AddHotspotUserResponse, error)
	RemoveHotspotUser(context.Context, *RemoveHotspotUserRequest) (*RemoveHotspotUserResponse, error)
	// Suspend/restore a hotspot customer without deleting their account —
	// mirrors DisablePppSecret/EnablePppSecret below. Needed by
	// payment-service's billing overdue-suspension flow (billing customers
	// whose `type` is 'hotspot' rather than 'pppoe').
	DisableHotspotUser(context.Context, *DisableHotspotUserRequest) (*DisableHotspotUserResponse, error)
	EnableHotspotUser(context.Context, *EnableHotspotUserRequest) (*EnableHotspotUserResponse, error)
	// Hotspot profiles
	ListHotspotProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error)
	GetHotspotProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	// Generic field-passthrough CRUD, mirroring AddPppProfile/UpdatePppProfile/
	// DeletePppProfile below — Go doesn't understand MikHMon's on-login script
	// metadata (price/validity/expiry mode encoded into the script text), it
	// just writes whatever `on_login` string the caller built. That business
	// logic lives in erp-node-service (ported from the monolith's
	// buildOnLoginScript/parseOnLogin), not here — same "smart client, dumb
	// server" split used for router-session management.
	AddHotspotProfile(context.Context, *AddHotspotProfileRequest) (*AddHotspotProfileResponse, error)
	UpdateHotspotProfile(context.Context, *UpdateHotspotProfileRequest) (*UpdateHotspotProfileResponse, error)
	DeleteHotspotProfile(context.Context, *DeleteHotspotProfileRequest) (*DeleteHotspotProfileResponse, error)
	// Bulk-remove — just RemoveHotspotUser looped server-side so the caller
	// makes one round-trip instead of N.
	BulkRemoveHotspotUsers(context.Context, *BulkRemoveHotspotUsersRequest) (*BulkRemoveHotspotUsersResponse, error)
	// Idempotent: creates the "mikhmon-cleanup-expired" scheduler if missing,
	// otherwise just re-confirms it (used after every profile save, matching
	// the monolith calling this on every add/edit). The cleanup script itself
	// is fixed/static (no customer input), so it's hardcoded here rather than
	// sent over the wire from erp-node-service.
	SetupExpiryScheduler(context.Context, *SetupExpirySchedulerRequest) (*SetupExpirySchedulerResponse, error)
	// System info
	GetSystemResource(context.Context, *SystemResourceRequest) (*SystemResourceResponse, error)
	GetInterfaces(context.Context, *InterfacesRequest) (*InterfacesResponse, error)
	// Router session management (CRUD) — the router connection profiles
	// (id, ip, credentials, hotspot/UI settings) that every other RPC above
	// is dialed against via session_id.
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	UpdateSession(context.Context, *UpdateSessionRequest) (*UpdateSessionResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	// ── PPPoE secrets ────────────────────────────────────────────────
	ListPppSecrets(context.Context, *ListPppSecretsRequest) (*ListPppSecretsResponse, error)
	GetPppSecret(context.Context, *GetPppSecretRequest) (*GetPppSecretResponse, error)
	AddPppSecret(context.Context, *AddPppSecretRequest) (*AddPppSecretResponse, error)
	UpdatePppSecret(context.Context, *UpdatePppSecretRequest) (*UpdatePppSecretResponse, error)
	DeletePppSecret(context.Context, *DeletePppSecretRequest) (*DeletePppSecretResponse, error)
	EnablePppSecret(context.Context, *EnablePppSecretRequest) (*EnablePppSecretResponse, error)
	DisablePppSecret(context.Context, *DisablePppSecretRequest) (*DisablePppSecretResponse, error)
	// ── PPPoE profiles ───────────────────────────────────────────────
	ListPppProfiles(context.Context, *ListPppProfilesRequest) (*ListPppProfilesResponse, error)
	AddPppProfile(context.Context, *AddPppProfileRequest) (*AddPppProfileResponse, error)
	UpdatePppProfile(context.Context, *UpdatePppProfileRequest) (*UpdatePppProfileResponse, error)
	DeletePppProfile(context.Context, *DeletePppProfileRequest) (*DeletePppProfileResponse, error)
	// ── PPPoE active conns & pools ───────────────────────────────────
	ListPppActive(context.Context, *ListPppActiveRequest) (*ListPppActiveResponse, error)
	DisconnectPppActive(context.Context, *DisconnectPppActiveRequest) (*DisconnectPppActiveResponse, error)
	ListPppPools(context.Context, *ListPppPoolsRequest) (*ListPppPoolsResponse, error)
	mustEmbedUnimplementedRouterServiceServer()
}

// UnimplementedRouterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRouterServiceServer struct {
}

func (UnimplementedRouterServiceServer) TestConnect(context.Context, *TestConnectRequest) (*TestConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestConnect not implemented")
}
func (UnimplementedRouterServiceServer) GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboard not implemented")
}
func (UnimplementedRouterServiceServer) ListActiveHotspotUsers(context.Context, *ListActiveRequest) (*ListActiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActiveHotspotUsers not implemented")
}
func (UnimplementedRouterServiceServer) ListHotspotUsers(context.Context, *ListHotspotUsersRequest) (*ListHotspotUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHotspotUsers not implemented")
}
func (UnimplementedRouterServiceServer) AddHotspotUser(context.Context, *AddHotspotUserRequest) (*AddHotspotUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHotspotUser not implemented")
}
func (UnimplementedRouterServiceServer) RemoveHotspotUser(context.Context, *RemoveHotspotUserRequest) (*RemoveHotspotUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveHotspotUser not implemented")
}
func (UnimplementedRouterServiceServer) DisableHotspotUser(context.Context, *DisableHotspotUserRequest) (*DisableHotspotUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableHotspotUser not implemented")
}
func (UnimplementedRouterServiceServer) EnableHotspotUser(context.Context, *EnableHotspotUserRequest) (*EnableHotspotUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableHotspotUser not implemented")
}
func (UnimplementedRouterServiceServer) ListHotspotProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHotspotProfiles not implemented")
}
func (UnimplementedRouterServiceServer) GetHotspotProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHotspotProfile not implemented")
}
func (UnimplementedRouterServiceServer) AddHotspotProfile(context.Context, *AddHotspotProfileRequest) (*AddHotspotProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHotspotProfile not implemented")
}
func (UnimplementedRouterServiceServer) UpdateHotspotProfile(context.Context, *UpdateHotspotProfileRequest) (*UpdateHotspotProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHotspotProfile not implemented")
}
func (UnimplementedRouterServiceServer) DeleteHotspotProfile(context.Context, *DeleteHotspotProfileRequest) (*DeleteHotspotProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHotspotProfile not implemented")
}
func (UnimplementedRouterServiceServer) BulkRemoveHotspotUsers(context.Context, *BulkRemoveHotspotUsersRequest) (*BulkRemoveHotspotUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkRemoveHotspotUsers not implemented")
}
func (UnimplementedRouterServiceServer) SetupExpiryScheduler(context.Context, *SetupExpirySchedulerRequest) (*SetupExpirySchedulerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupExpiryScheduler not implemented")
}
func (UnimplementedRouterServiceServer) GetSystemResource(context.Context, *SystemResourceRequest) (*SystemResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemResource not implemented")
}
func (UnimplementedRouterServiceServer) GetInterfaces(context.Context, *InterfacesRequest) (*InterfacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInterfaces not implemented")
}
func (UnimplementedRouterServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedRouterServiceServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedRouterServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedRouterServiceServer) UpdateSession(context.Context, *UpdateSessionRequest) (*UpdateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSession not implemented")
}
func (UnimplementedRouterServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedRouterServiceServer) ListPppSecrets(context.Context, *ListPppSecretsRequest) (*ListPppSecretsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPppSecrets not implemented")
}
func (UnimplementedRouterServiceServer) GetPppSecret(context.Context, *GetPppSecretRequest) (*GetPppSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPppSecret not implemented")
}
func (UnimplementedRouterServiceServer) AddPppSecret(context.Context, *AddPppSecretRequest) (*AddPppSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPppSecret not implemented")
}
func (UnimplementedRouterServiceServer) UpdatePppSecret(context.Context, *UpdatePppSecretRequest) (*UpdatePppSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePppSecret not implemented")
}
func (UnimplementedRouterServiceServer) DeletePppSecret(context.Context, *DeletePppSecretRequest) (*DeletePppSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePppSecret not implemented")
}
func (UnimplementedRouterServiceServer) EnablePppSecret(context.Context, *EnablePppSecretRequest) (*EnablePppSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnablePppSecret not implemented")
}
func (UnimplementedRouterServiceServer) DisablePppSecret(context.Context, *DisablePppSecretRequest) (*DisablePppSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisablePppSecret not implemented")
}
func (UnimplementedRouterServiceServer) ListPppProfiles(context.Context, *ListPppProfilesRequest) (*ListPppProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPppProfiles not implemented")
}
func (UnimplementedRouterServiceServer) AddPppProfile(context.Context, *AddPppProfileRequest) (*AddPppProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPppProfile not implemented")
}
func (UnimplementedRouterServiceServer) UpdatePppProfile(context.Context, *UpdatePppProfileRequest) (*UpdatePppProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePppProfile not implemented")
}
func (UnimplementedRouterServiceServer) DeletePppProfile(context.Context, *DeletePppProfileRequest) (*DeletePppProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePppProfile not implemented")
}
func (UnimplementedRouterServiceServer) ListPppActive(context.Context, *ListPppActiveRequest) (*ListPppActiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPppActive not implemented")
}
func (UnimplementedRouterServiceServer) DisconnectPppActive(context.Context, *DisconnectPppActiveRequest) (*DisconnectPppActiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisconnectPppActive not implemented")
}
func (UnimplementedRouterServiceServer) ListPppPools(context.Context, *ListPppPoolsRequest) (*ListPppPoolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPppPools not implemented")
}
func (UnimplementedRouterServiceServer) mustEmbedUnimplementedRouterServiceServer() {}

// UnsafeRouterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouterServiceServer will
// result in compilation errors.
type UnsafeRouterServiceServer interface {
	mustEmbedUnimplementedRouterServiceServer()
}

func RegisterRouterServiceServer(s *grpc.Server, srv RouterServiceServer) {
	s.RegisterService(&_RouterService_serviceDesc, srv)
}

func _RouterService_TestConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).TestConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/TestConnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).TestConnect(ctx, req.(*TestConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/GetDashboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetDashboard(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListActiveHotspotUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListActiveHotspotUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/ListActiveHotspotUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListActiveHotspotUsers(ctx, req.(*ListActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListHotspotUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHotspotUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListHotspotUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/ListHotspotUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListHotspotUsers(ctx, req.(*ListHotspotUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_AddHotspotUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHotspotUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).AddHotspotUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/AddHotspotUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).AddHotspotUser(ctx, req.(*AddHotspotUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_RemoveHotspotUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveHotspotUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).RemoveHotspotUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/RemoveHotspotUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).RemoveHotspotUser(ctx, req.(*RemoveHotspotUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_DisableHotspotUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableHotspotUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).DisableHotspotUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/DisableHotspotUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).DisableHotspotUser(ctx, req.(*DisableHotspotUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_EnableHotspotUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableHotspotUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).EnableHotspotUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/EnableHotspotUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).EnableHotspotUser(ctx, req.(*EnableHotspotUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListHotspotProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListHotspotProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/ListHotspotProfiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListHotspotProfiles(ctx, req.(*ListProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetHotspotProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetHotspotProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/GetHotspotProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetHotspotProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_AddHotspotProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHotspotProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).AddHotspotProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/AddHotspotProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).AddHotspotProfile(ctx, req.(*AddHotspotProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_UpdateHotspotProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHotspotProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).UpdateHotspotProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/UpdateHotspotProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).UpdateHotspotProfile(ctx, req.(*UpdateHotspotProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_DeleteHotspotProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHotspotProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).DeleteHotspotProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/DeleteHotspotProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).DeleteHotspotProfile(ctx, req.(*DeleteHotspotProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_BulkRemoveHotspotUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkRemoveHotspotUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).BulkRemoveHotspotUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/BulkRemoveHotspotUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).BulkRemoveHotspotUsers(ctx, req.(*BulkRemoveHotspotUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_SetupExpiryScheduler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupExpirySchedulerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).SetupExpiryScheduler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/SetupExpiryScheduler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).SetupExpiryScheduler(ctx, req.(*SetupExpirySchedulerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetSystemResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetSystemResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/GetSystemResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetSystemResource(ctx, req.(*SystemResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/GetInterfaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetInterfaces(ctx, req.(*InterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/ListSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/GetSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_UpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).UpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/UpdateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).UpdateSession(ctx, req.(*UpdateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/DeleteSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListPppSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPppSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListPppSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/ListPppSecrets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListPppSecrets(ctx, req.(*ListPppSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetPppSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPppSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetPppSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/GetPppSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetPppSecret(ctx, req.(*GetPppSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_AddPppSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPppSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).AddPppSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/AddPppSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).AddPppSecret(ctx, req.(*AddPppSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_UpdatePppSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePppSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).UpdatePppSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/UpdatePppSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).UpdatePppSecret(ctx, req.(*UpdatePppSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_DeletePppSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePppSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).DeletePppSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/DeletePppSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).DeletePppSecret(ctx, req.(*DeletePppSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_EnablePppSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnablePppSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).EnablePppSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/EnablePppSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).EnablePppSecret(ctx, req.(*EnablePppSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_DisablePppSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisablePppSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).DisablePppSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/DisablePppSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).DisablePppSecret(ctx, req.(*DisablePppSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListPppProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPppProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListPppProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/ListPppProfiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListPppProfiles(ctx, req.(*ListPppProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_AddPppProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPppProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).AddPppProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/AddPppProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).AddPppProfile(ctx, req.(*AddPppProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_UpdatePppProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePppProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).UpdatePppProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/UpdatePppProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).UpdatePppProfile(ctx, req.(*UpdatePppProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_DeletePppProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePppProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).DeletePppProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/DeletePppProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).DeletePppProfile(ctx, req.(*DeletePppProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListPppActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPppActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListPppActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/ListPppActive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListPppActive(ctx, req.(*ListPppActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_DisconnectPppActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectPppActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).DisconnectPppActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/DisconnectPppActive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).DisconnectPppActive(ctx, req.(*DisconnectPppActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListPppPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPppPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListPppPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.RouterService/ListPppPools",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListPppPools(ctx, req.(*ListPppPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RouterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "router.RouterService",
	HandlerType: (*RouterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestConnect",
			Handler:    _RouterService_TestConnect_Handler,
		},
		{
			MethodName: "GetDashboard",
			Handler:    _RouterService_GetDashboard_Handler,
		},
		{
			MethodName: "ListActiveHotspotUsers",
			Handler:    _RouterService_ListActiveHotspotUsers_Handler,
		},
		{
			MethodName: "ListHotspotUsers",
			Handler:    _RouterService_ListHotspotUsers_Handler,
		},
		{
			MethodName: "AddHotspotUser",
			Handler:    _RouterService_AddHotspotUser_Handler,
		},
		{
			MethodName: "RemoveHotspotUser",
			Handler:    _RouterService_RemoveHotspotUser_Handler,
		},
		{
			MethodName: "DisableHotspotUser",
			Handler:    _RouterService_DisableHotspotUser_Handler,
		},
		{
			MethodName: "EnableHotspotUser",
			Handler:    _RouterService_EnableHotspotUser_Handler,
		},
		{
			MethodName: "ListHotspotProfiles",
			Handler:    _RouterService_ListHotspotProfiles_Handler,
		},
		{
			MethodName: "GetHotspotProfile",
			Handler:    _RouterService_GetHotspotProfile_Handler,
		},
		{
			MethodName: "AddHotspotProfile",
			Handler:    _RouterService_AddHotspotProfile_Handler,
		},
		{
			MethodName: "UpdateHotspotProfile",
			Handler:    _RouterService_UpdateHotspotProfile_Handler,
		},
		{
			MethodName: "DeleteHotspotProfile",
			Handler:    _RouterService_DeleteHotspotProfile_Handler,
		},
		{
			MethodName: "BulkRemoveHotspotUsers",
			Handler:    _RouterService_BulkRemoveHotspotUsers_Handler,
		},
		{
			MethodName: "SetupExpiryScheduler",
			Handler:    _RouterService_SetupExpiryScheduler_Handler,
		},
		{
			MethodName: "GetSystemResource",
			Handler:    _RouterService_GetSystemResource_Handler,
		},
		{
			MethodName: "GetInterfaces",
			Handler:    _RouterService_GetInterfaces_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _RouterService_ListSessions_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _RouterService_GetSession_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _RouterService_CreateSession_Handler,
		},
		{
			MethodName: "UpdateSession",
			Handler:    _RouterService_UpdateSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _RouterService_DeleteSession_Handler,
		},
		{
			MethodName: "ListPppSecrets",
			Handler:    _RouterService_ListPppSecrets_Handler,
		},
		{
			MethodName: "GetPppSecret",
			Handler:    _RouterService_GetPppSecret_Handler,
		},
		{
			MethodName: "AddPppSecret",
			Handler:    _RouterService_AddPppSecret_Handler,
		},
		{
			MethodName: "UpdatePppSecret",
			Handler:    _RouterService_UpdatePppSecret_Handler,
		},
		{
			MethodName: "DeletePppSecret",
			Handler:    _RouterService_DeletePppSecret_Handler,
		},
		{
			MethodName: "EnablePppSecret",
			Handler:    _RouterService_EnablePppSecret_Handler,
		},
		{
			MethodName: "DisablePppSecret",
			Handler:    _RouterService_DisablePppSecret_Handler,
		},
		{
			MethodName: "ListPppProfiles",
			Handler:    _RouterService_ListPppProfiles_Handler,
		},
		{
			MethodName: "AddPppProfile",
			Handler:    _RouterService_AddPppProfile_Handler,
		},
		{
			MethodName: "UpdatePppProfile",
			Handler:    _RouterService_UpdatePppProfile_Handler,
		},
		{
			MethodName: "DeletePppProfile",
			Handler:    _RouterService_DeletePppProfile_Handler,
		},
		{
			MethodName: "ListPppActive",
			Handler:    _RouterService_ListPppActive_Handler,
		},
		{
			MethodName: "DisconnectPppActive",
			Handler:    _RouterService_DisconnectPppActive_Handler,
		},
		{
			MethodName: "ListPppPools",
			Handler:    _RouterService_ListPppPools_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "router.proto",
}
