// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/router.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RouterService_TestConnect_FullMethodName            = "/router.RouterService/TestConnect"
	RouterService_GetDashboard_FullMethodName           = "/router.RouterService/GetDashboard"
	RouterService_ListActiveHotspotUsers_FullMethodName = "/router.RouterService/ListActiveHotspotUsers"
	RouterService_ListHotspotUsers_FullMethodName       = "/router.RouterService/ListHotspotUsers"
	RouterService_AddHotspotUser_FullMethodName         = "/router.RouterService/AddHotspotUser"
	RouterService_RemoveHotspotUser_FullMethodName      = "/router.RouterService/RemoveHotspotUser"
	RouterService_ListHotspotProfiles_FullMethodName    = "/router.RouterService/ListHotspotProfiles"
	RouterService_GetHotspotProfile_FullMethodName      = "/router.RouterService/GetHotspotProfile"
	RouterService_GetSystemResource_FullMethodName      = "/router.RouterService/GetSystemResource"
	RouterService_GetInterfaces_FullMethodName          = "/router.RouterService/GetInterfaces"
)

// RouterServiceClient is the client API for RouterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RouterService exposes MikroTik operations to other microservices
// (payment-service, erp-node-service, main-node-service) via gRPC.
type RouterServiceClient interface {
	// Connection test
	TestConnect(ctx context.Context, in *TestConnectRequest, opts ...grpc.CallOption) (*TestConnectResponse, error)
	// Dashboard
	GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardResponse, error)
	// Hotspot users
	ListActiveHotspotUsers(ctx context.Context, in *ListActiveRequest, opts ...grpc.CallOption) (*ListActiveResponse, error)
	ListHotspotUsers(ctx context.Context, in *ListHotspotUsersRequest, opts ...grpc.CallOption) (*ListHotspotUsersResponse, error)
	AddHotspotUser(ctx context.Context, in *AddHotspotUserRequest, opts ...grpc.CallOption) (*AddHotspotUserResponse, error)
	RemoveHotspotUser(ctx context.Context, in *RemoveHotspotUserRequest, opts ...grpc.CallOption) (*RemoveHotspotUserResponse, error)
	// Hotspot profiles
	ListHotspotProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error)
	GetHotspotProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	// System info
	GetSystemResource(ctx context.Context, in *SystemResourceRequest, opts ...grpc.CallOption) (*SystemResourceResponse, error)
	GetInterfaces(ctx context.Context, in *InterfacesRequest, opts ...grpc.CallOption) (*InterfacesResponse, error)
}

type routerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterServiceClient(cc grpc.ClientConnInterface) RouterServiceClient {
	return &routerServiceClient{cc}
}

func (c *routerServiceClient) TestConnect(ctx context.Context, in *TestConnectRequest, opts ...grpc.CallOption) (*TestConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestConnectResponse)
	err := c.cc.Invoke(ctx, RouterService_TestConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardResponse)
	err := c.cc.Invoke(ctx, RouterService_GetDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListActiveHotspotUsers(ctx context.Context, in *ListActiveRequest, opts ...grpc.CallOption) (*ListActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveResponse)
	err := c.cc.Invoke(ctx, RouterService_ListActiveHotspotUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListHotspotUsers(ctx context.Context, in *ListHotspotUsersRequest, opts ...grpc.CallOption) (*ListHotspotUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHotspotUsersResponse)
	err := c.cc.Invoke(ctx, RouterService_ListHotspotUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) AddHotspotUser(ctx context.Context, in *AddHotspotUserRequest, opts ...grpc.CallOption) (*AddHotspotUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddHotspotUserResponse)
	err := c.cc.Invoke(ctx, RouterService_AddHotspotUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) RemoveHotspotUser(ctx context.Context, in *RemoveHotspotUserRequest, opts ...grpc.CallOption) (*RemoveHotspotUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveHotspotUserResponse)
	err := c.cc.Invoke(ctx, RouterService_RemoveHotspotUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListHotspotProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, RouterService_ListHotspotProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetHotspotProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, RouterService_GetHotspotProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetSystemResource(ctx context.Context, in *SystemResourceRequest, opts ...grpc.CallOption) (*SystemResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemResourceResponse)
	err := c.cc.Invoke(ctx, RouterService_GetSystemResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetInterfaces(ctx context.Context, in *InterfacesRequest, opts ...grpc.CallOption) (*InterfacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterfacesResponse)
	err := c.cc.Invoke(ctx, RouterService_GetInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServiceServer is the server API for RouterService service.
// All implementations must embed UnimplementedRouterServiceServer
// for forward compatibility.
//
// RouterService exposes MikroTik operations to other microservices
// (payment-service, erp-node-service, main-node-service) via gRPC.
type RouterServiceServer interface {
	// Connection test
	TestConnect(context.Context, *TestConnectRequest) (*TestConnectResponse, error)
	// Dashboard
	GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardResponse, error)
	// Hotspot users
	ListActiveHotspotUsers(context.Context, *ListActiveRequest) (*ListActiveResponse, error)
	ListHotspotUsers(context.Context, *ListHotspotUsersRequest) (*ListHotspotUsersResponse, error)
	AddHotspotUser(context.Context, *AddHotspotUserRequest) (*AddHotspotUserResponse, error)
	RemoveHotspotUser(context.Context, *RemoveHotspotUserRequest) (*RemoveHotspotUserResponse, error)
	// Hotspot profiles
	ListHotspotProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error)
	GetHotspotProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	// System info
	GetSystemResource(context.Context, *SystemResourceRequest) (*SystemResourceResponse, error)
	GetInterfaces(context.Context, *InterfacesRequest) (*InterfacesResponse, error)
	mustEmbedUnimplementedRouterServiceServer()
}

// UnimplementedRouterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouterServiceServer struct{}

func (UnimplementedRouterServiceServer) TestConnect(context.Context, *TestConnectRequest) (*TestConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestConnect not implemented")
}
func (UnimplementedRouterServiceServer) GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboard not implemented")
}
func (UnimplementedRouterServiceServer) ListActiveHotspotUsers(context.Context, *ListActiveRequest) (*ListActiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActiveHotspotUsers not implemented")
}
func (UnimplementedRouterServiceServer) ListHotspotUsers(context.Context, *ListHotspotUsersRequest) (*ListHotspotUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHotspotUsers not implemented")
}
func (UnimplementedRouterServiceServer) AddHotspotUser(context.Context, *AddHotspotUserRequest) (*AddHotspotUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddHotspotUser not implemented")
}
func (UnimplementedRouterServiceServer) RemoveHotspotUser(context.Context, *RemoveHotspotUserRequest) (*RemoveHotspotUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveHotspotUser not implemented")
}
func (UnimplementedRouterServiceServer) ListHotspotProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHotspotProfiles not implemented")
}
func (UnimplementedRouterServiceServer) GetHotspotProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHotspotProfile not implemented")
}
func (UnimplementedRouterServiceServer) GetSystemResource(context.Context, *SystemResourceRequest) (*SystemResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemResource not implemented")
}
func (UnimplementedRouterServiceServer) GetInterfaces(context.Context, *InterfacesRequest) (*InterfacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterfaces not implemented")
}
func (UnimplementedRouterServiceServer) mustEmbedUnimplementedRouterServiceServer() {}
func (UnimplementedRouterServiceServer) testEmbeddedByValue()                       {}

// UnsafeRouterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouterServiceServer will
// result in compilation errors.
type UnsafeRouterServiceServer interface {
	mustEmbedUnimplementedRouterServiceServer()
}

func RegisterRouterServiceServer(s grpc.ServiceRegistrar, srv RouterServiceServer) {
	// If the following call panics, it indicates UnimplementedRouterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouterService_ServiceDesc, srv)
}

func _RouterService_TestConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).TestConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_TestConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).TestConnect(ctx, req.(*TestConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_GetDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetDashboard(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListActiveHotspotUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListActiveHotspotUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_ListActiveHotspotUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListActiveHotspotUsers(ctx, req.(*ListActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListHotspotUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHotspotUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListHotspotUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_ListHotspotUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListHotspotUsers(ctx, req.(*ListHotspotUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_AddHotspotUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHotspotUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).AddHotspotUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_AddHotspotUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).AddHotspotUser(ctx, req.(*AddHotspotUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_RemoveHotspotUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveHotspotUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).RemoveHotspotUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_RemoveHotspotUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).RemoveHotspotUser(ctx, req.(*RemoveHotspotUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListHotspotProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListHotspotProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_ListHotspotProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListHotspotProfiles(ctx, req.(*ListProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetHotspotProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetHotspotProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_GetHotspotProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetHotspotProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetSystemResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetSystemResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_GetSystemResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetSystemResource(ctx, req.(*SystemResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_GetInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetInterfaces(ctx, req.(*InterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RouterService_ServiceDesc is the grpc.ServiceDesc for RouterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "router.RouterService",
	HandlerType: (*RouterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestConnect",
			Handler:    _RouterService_TestConnect_Handler,
		},
		{
			MethodName: "GetDashboard",
			Handler:    _RouterService_GetDashboard_Handler,
		},
		{
			MethodName: "ListActiveHotspotUsers",
			Handler:    _RouterService_ListActiveHotspotUsers_Handler,
		},
		{
			MethodName: "ListHotspotUsers",
			Handler:    _RouterService_ListHotspotUsers_Handler,
		},
		{
			MethodName: "AddHotspotUser",
			Handler:    _RouterService_AddHotspotUser_Handler,
		},
		{
			MethodName: "RemoveHotspotUser",
			Handler:    _RouterService_RemoveHotspotUser_Handler,
		},
		{
			MethodName: "ListHotspotProfiles",
			Handler:    _RouterService_ListHotspotProfiles_Handler,
		},
		{
			MethodName: "GetHotspotProfile",
			Handler:    _RouterService_GetHotspotProfile_Handler,
		},
		{
			MethodName: "GetSystemResource",
			Handler:    _RouterService_GetSystemResource_Handler,
		},
		{
			MethodName: "GetInterfaces",
			Handler:    _RouterService_GetInterfaces_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/router.proto",
}
