// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/router.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RouterService_TestConnect_FullMethodName            = "/router.RouterService/TestConnect"
	RouterService_GetDashboard_FullMethodName           = "/router.RouterService/GetDashboard"
	RouterService_ListActiveHotspotUsers_FullMethodName = "/router.RouterService/ListActiveHotspotUsers"
	RouterService_ListHotspotUsers_FullMethodName       = "/router.RouterService/ListHotspotUsers"
	RouterService_AddHotspotUser_FullMethodName         = "/router.RouterService/AddHotspotUser"
	RouterService_RemoveHotspotUser_FullMethodName      = "/router.RouterService/RemoveHotspotUser"
	RouterService_ListHotspotProfiles_FullMethodName    = "/router.RouterService/ListHotspotProfiles"
	RouterService_GetHotspotProfile_FullMethodName      = "/router.RouterService/GetHotspotProfile"
	RouterService_GetSystemResource_FullMethodName      = "/router.RouterService/GetSystemResource"
	RouterService_GetInterfaces_FullMethodName          = "/router.RouterService/GetInterfaces"
	RouterService_ListSessions_FullMethodName           = "/router.RouterService/ListSessions"
	RouterService_GetSession_FullMethodName             = "/router.RouterService/GetSession"
	RouterService_CreateSession_FullMethodName          = "/router.RouterService/CreateSession"
	RouterService_UpdateSession_FullMethodName          = "/router.RouterService/UpdateSession"
	RouterService_DeleteSession_FullMethodName          = "/router.RouterService/DeleteSession"
	RouterService_ListPppSecrets_FullMethodName         = "/router.RouterService/ListPppSecrets"
	RouterService_GetPppSecret_FullMethodName           = "/router.RouterService/GetPppSecret"
	RouterService_AddPppSecret_FullMethodName           = "/router.RouterService/AddPppSecret"
	RouterService_UpdatePppSecret_FullMethodName        = "/router.RouterService/UpdatePppSecret"
	RouterService_DeletePppSecret_FullMethodName        = "/router.RouterService/DeletePppSecret"
	RouterService_EnablePppSecret_FullMethodName        = "/router.RouterService/EnablePppSecret"
	RouterService_DisablePppSecret_FullMethodName       = "/router.RouterService/DisablePppSecret"
	RouterService_ListPppProfiles_FullMethodName        = "/router.RouterService/ListPppProfiles"
	RouterService_AddPppProfile_FullMethodName          = "/router.RouterService/AddPppProfile"
	RouterService_UpdatePppProfile_FullMethodName       = "/router.RouterService/UpdatePppProfile"
	RouterService_DeletePppProfile_FullMethodName       = "/router.RouterService/DeletePppProfile"
	RouterService_ListPppActive_FullMethodName          = "/router.RouterService/ListPppActive"
	RouterService_DisconnectPppActive_FullMethodName    = "/router.RouterService/DisconnectPppActive"
	RouterService_ListPppPools_FullMethodName           = "/router.RouterService/ListPppPools"
)

// RouterServiceClient is the client API for RouterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RouterService exposes MikroTik operations to other microservices
// (payment-service, erp-node-service, main-node-service) via gRPC.
type RouterServiceClient interface {
	// Connection test
	TestConnect(ctx context.Context, in *TestConnectRequest, opts ...grpc.CallOption) (*TestConnectResponse, error)
	// Dashboard
	GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardResponse, error)
	// Hotspot users
	ListActiveHotspotUsers(ctx context.Context, in *ListActiveRequest, opts ...grpc.CallOption) (*ListActiveResponse, error)
	ListHotspotUsers(ctx context.Context, in *ListHotspotUsersRequest, opts ...grpc.CallOption) (*ListHotspotUsersResponse, error)
	AddHotspotUser(ctx context.Context, in *AddHotspotUserRequest, opts ...grpc.CallOption) (*AddHotspotUserResponse, error)
	RemoveHotspotUser(ctx context.Context, in *RemoveHotspotUserRequest, opts ...grpc.CallOption) (*RemoveHotspotUserResponse, error)
	// Hotspot profiles
	ListHotspotProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error)
	GetHotspotProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	// System info
	GetSystemResource(ctx context.Context, in *SystemResourceRequest, opts ...grpc.CallOption) (*SystemResourceResponse, error)
	GetInterfaces(ctx context.Context, in *InterfacesRequest, opts ...grpc.CallOption) (*InterfacesResponse, error)
	// Router session management (CRUD) — the router connection profiles
	// (id, ip, credentials, hotspot/UI settings) that every other RPC above
	// is dialed against via session_id.
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*UpdateSessionResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	// ── PPPoE secrets ────────────────────────────────────────────────
	ListPppSecrets(ctx context.Context, in *ListPppSecretsRequest, opts ...grpc.CallOption) (*ListPppSecretsResponse, error)
	GetPppSecret(ctx context.Context, in *GetPppSecretRequest, opts ...grpc.CallOption) (*GetPppSecretResponse, error)
	AddPppSecret(ctx context.Context, in *AddPppSecretRequest, opts ...grpc.CallOption) (*AddPppSecretResponse, error)
	UpdatePppSecret(ctx context.Context, in *UpdatePppSecretRequest, opts ...grpc.CallOption) (*UpdatePppSecretResponse, error)
	DeletePppSecret(ctx context.Context, in *DeletePppSecretRequest, opts ...grpc.CallOption) (*DeletePppSecretResponse, error)
	EnablePppSecret(ctx context.Context, in *EnablePppSecretRequest, opts ...grpc.CallOption) (*EnablePppSecretResponse, error)
	DisablePppSecret(ctx context.Context, in *DisablePppSecretRequest, opts ...grpc.CallOption) (*DisablePppSecretResponse, error)
	// ── PPPoE profiles ───────────────────────────────────────────────
	ListPppProfiles(ctx context.Context, in *ListPppProfilesRequest, opts ...grpc.CallOption) (*ListPppProfilesResponse, error)
	AddPppProfile(ctx context.Context, in *AddPppProfileRequest, opts ...grpc.CallOption) (*AddPppProfileResponse, error)
	UpdatePppProfile(ctx context.Context, in *UpdatePppProfileRequest, opts ...grpc.CallOption) (*UpdatePppProfileResponse, error)
	DeletePppProfile(ctx context.Context, in *DeletePppProfileRequest, opts ...grpc.CallOption) (*DeletePppProfileResponse, error)
	// ── PPPoE active conns & pools ───────────────────────────────────
	ListPppActive(ctx context.Context, in *ListPppActiveRequest, opts ...grpc.CallOption) (*ListPppActiveResponse, error)
	DisconnectPppActive(ctx context.Context, in *DisconnectPppActiveRequest, opts ...grpc.CallOption) (*DisconnectPppActiveResponse, error)
	ListPppPools(ctx context.Context, in *ListPppPoolsRequest, opts ...grpc.CallOption) (*ListPppPoolsResponse, error)
}

type routerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterServiceClient(cc grpc.ClientConnInterface) RouterServiceClient {
	return &routerServiceClient{cc}
}

func (c *routerServiceClient) TestConnect(ctx context.Context, in *TestConnectRequest, opts ...grpc.CallOption) (*TestConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestConnectResponse)
	err := c.cc.Invoke(ctx, RouterService_TestConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardResponse)
	err := c.cc.Invoke(ctx, RouterService_GetDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListActiveHotspotUsers(ctx context.Context, in *ListActiveRequest, opts ...grpc.CallOption) (*ListActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveResponse)
	err := c.cc.Invoke(ctx, RouterService_ListActiveHotspotUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListHotspotUsers(ctx context.Context, in *ListHotspotUsersRequest, opts ...grpc.CallOption) (*ListHotspotUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHotspotUsersResponse)
	err := c.cc.Invoke(ctx, RouterService_ListHotspotUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) AddHotspotUser(ctx context.Context, in *AddHotspotUserRequest, opts ...grpc.CallOption) (*AddHotspotUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddHotspotUserResponse)
	err := c.cc.Invoke(ctx, RouterService_AddHotspotUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) RemoveHotspotUser(ctx context.Context, in *RemoveHotspotUserRequest, opts ...grpc.CallOption) (*RemoveHotspotUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveHotspotUserResponse)
	err := c.cc.Invoke(ctx, RouterService_RemoveHotspotUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListHotspotProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, RouterService_ListHotspotProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetHotspotProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, RouterService_GetHotspotProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetSystemResource(ctx context.Context, in *SystemResourceRequest, opts ...grpc.CallOption) (*SystemResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemResourceResponse)
	err := c.cc.Invoke(ctx, RouterService_GetSystemResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetInterfaces(ctx context.Context, in *InterfacesRequest, opts ...grpc.CallOption) (*InterfacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterfacesResponse)
	err := c.cc.Invoke(ctx, RouterService_GetInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, RouterService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, RouterService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, RouterService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*UpdateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSessionResponse)
	err := c.cc.Invoke(ctx, RouterService_UpdateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, RouterService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListPppSecrets(ctx context.Context, in *ListPppSecretsRequest, opts ...grpc.CallOption) (*ListPppSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPppSecretsResponse)
	err := c.cc.Invoke(ctx, RouterService_ListPppSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetPppSecret(ctx context.Context, in *GetPppSecretRequest, opts ...grpc.CallOption) (*GetPppSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPppSecretResponse)
	err := c.cc.Invoke(ctx, RouterService_GetPppSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) AddPppSecret(ctx context.Context, in *AddPppSecretRequest, opts ...grpc.CallOption) (*AddPppSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPppSecretResponse)
	err := c.cc.Invoke(ctx, RouterService_AddPppSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) UpdatePppSecret(ctx context.Context, in *UpdatePppSecretRequest, opts ...grpc.CallOption) (*UpdatePppSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePppSecretResponse)
	err := c.cc.Invoke(ctx, RouterService_UpdatePppSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) DeletePppSecret(ctx context.Context, in *DeletePppSecretRequest, opts ...grpc.CallOption) (*DeletePppSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePppSecretResponse)
	err := c.cc.Invoke(ctx, RouterService_DeletePppSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) EnablePppSecret(ctx context.Context, in *EnablePppSecretRequest, opts ...grpc.CallOption) (*EnablePppSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnablePppSecretResponse)
	err := c.cc.Invoke(ctx, RouterService_EnablePppSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) DisablePppSecret(ctx context.Context, in *DisablePppSecretRequest, opts ...grpc.CallOption) (*DisablePppSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisablePppSecretResponse)
	err := c.cc.Invoke(ctx, RouterService_DisablePppSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListPppProfiles(ctx context.Context, in *ListPppProfilesRequest, opts ...grpc.CallOption) (*ListPppProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPppProfilesResponse)
	err := c.cc.Invoke(ctx, RouterService_ListPppProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) AddPppProfile(ctx context.Context, in *AddPppProfileRequest, opts ...grpc.CallOption) (*AddPppProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPppProfileResponse)
	err := c.cc.Invoke(ctx, RouterService_AddPppProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) UpdatePppProfile(ctx context.Context, in *UpdatePppProfileRequest, opts ...grpc.CallOption) (*UpdatePppProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePppProfileResponse)
	err := c.cc.Invoke(ctx, RouterService_UpdatePppProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) DeletePppProfile(ctx context.Context, in *DeletePppProfileRequest, opts ...grpc.CallOption) (*DeletePppProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePppProfileResponse)
	err := c.cc.Invoke(ctx, RouterService_DeletePppProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListPppActive(ctx context.Context, in *ListPppActiveRequest, opts ...grpc.CallOption) (*ListPppActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPppActiveResponse)
	err := c.cc.Invoke(ctx, RouterService_ListPppActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) DisconnectPppActive(ctx context.Context, in *DisconnectPppActiveRequest, opts ...grpc.CallOption) (*DisconnectPppActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectPppActiveResponse)
	err := c.cc.Invoke(ctx, RouterService_DisconnectPppActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ListPppPools(ctx context.Context, in *ListPppPoolsRequest, opts ...grpc.CallOption) (*ListPppPoolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPppPoolsResponse)
	err := c.cc.Invoke(ctx, RouterService_ListPppPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServiceServer is the server API for RouterService service.
// All implementations must embed UnimplementedRouterServiceServer
// for forward compatibility.
//
// RouterService exposes MikroTik operations to other microservices
// (payment-service, erp-node-service, main-node-service) via gRPC.
type RouterServiceServer interface {
	// Connection test
	TestConnect(context.Context, *TestConnectRequest) (*TestConnectResponse, error)
	// Dashboard
	GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardResponse, error)
	// Hotspot users
	ListActiveHotspotUsers(context.Context, *ListActiveRequest) (*ListActiveResponse, error)
	ListHotspotUsers(context.Context, *ListHotspotUsersRequest) (*ListHotspotUsersResponse, error)
	AddHotspotUser(context.Context, *AddHotspotUserRequest) (*AddHotspotUserResponse, error)
	RemoveHotspotUser(context.Context, *RemoveHotspotUserRequest) (*RemoveHotspotUserResponse, error)
	// Hotspot profiles
	ListHotspotProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error)
	GetHotspotProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	// System info
	GetSystemResource(context.Context, *SystemResourceRequest) (*SystemResourceResponse, error)
	GetInterfaces(context.Context, *InterfacesRequest) (*InterfacesResponse, error)
	// Router session management (CRUD) — the router connection profiles
	// (id, ip, credentials, hotspot/UI settings) that every other RPC above
	// is dialed against via session_id.
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	UpdateSession(context.Context, *UpdateSessionRequest) (*UpdateSessionResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	// ── PPPoE secrets ────────────────────────────────────────────────
	ListPppSecrets(context.Context, *ListPppSecretsRequest) (*ListPppSecretsResponse, error)
	GetPppSecret(context.Context, *GetPppSecretRequest) (*GetPppSecretResponse, error)
	AddPppSecret(context.Context, *AddPppSecretRequest) (*AddPppSecretResponse, error)
	UpdatePppSecret(context.Context, *UpdatePppSecretRequest) (*UpdatePppSecretResponse, error)
	DeletePppSecret(context.Context, *DeletePppSecretRequest) (*DeletePppSecretResponse, error)
	EnablePppSecret(context.Context, *EnablePppSecretRequest) (*EnablePppSecretResponse, error)
	DisablePppSecret(context.Context, *DisablePppSecretRequest) (*DisablePppSecretResponse, error)
	// ── PPPoE profiles ───────────────────────────────────────────────
	ListPppProfiles(context.Context, *ListPppProfilesRequest) (*ListPppProfilesResponse, error)
	AddPppProfile(context.Context, *AddPppProfileRequest) (*AddPppProfileResponse, error)
	UpdatePppProfile(context.Context, *UpdatePppProfileRequest) (*UpdatePppProfileResponse, error)
	DeletePppProfile(context.Context, *DeletePppProfileRequest) (*DeletePppProfileResponse, error)
	// ── PPPoE active conns & pools ───────────────────────────────────
	ListPppActive(context.Context, *ListPppActiveRequest) (*ListPppActiveResponse, error)
	DisconnectPppActive(context.Context, *DisconnectPppActiveRequest) (*DisconnectPppActiveResponse, error)
	ListPppPools(context.Context, *ListPppPoolsRequest) (*ListPppPoolsResponse, error)
	mustEmbedUnimplementedRouterServiceServer()
}

// UnimplementedRouterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouterServiceServer struct{}

func (UnimplementedRouterServiceServer) TestConnect(context.Context, *TestConnectRequest) (*TestConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestConnect not implemented")
}
func (UnimplementedRouterServiceServer) GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboard not implemented")
}
func (UnimplementedRouterServiceServer) ListActiveHotspotUsers(context.Context, *ListActiveRequest) (*ListActiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActiveHotspotUsers not implemented")
}
func (UnimplementedRouterServiceServer) ListHotspotUsers(context.Context, *ListHotspotUsersRequest) (*ListHotspotUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHotspotUsers not implemented")
}
func (UnimplementedRouterServiceServer) AddHotspotUser(context.Context, *AddHotspotUserRequest) (*AddHotspotUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddHotspotUser not implemented")
}
func (UnimplementedRouterServiceServer) RemoveHotspotUser(context.Context, *RemoveHotspotUserRequest) (*RemoveHotspotUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveHotspotUser not implemented")
}
func (UnimplementedRouterServiceServer) ListHotspotProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHotspotProfiles not implemented")
}
func (UnimplementedRouterServiceServer) GetHotspotProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHotspotProfile not implemented")
}
func (UnimplementedRouterServiceServer) GetSystemResource(context.Context, *SystemResourceRequest) (*SystemResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemResource not implemented")
}
func (UnimplementedRouterServiceServer) GetInterfaces(context.Context, *InterfacesRequest) (*InterfacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterfaces not implemented")
}
func (UnimplementedRouterServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedRouterServiceServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedRouterServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedRouterServiceServer) UpdateSession(context.Context, *UpdateSessionRequest) (*UpdateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSession not implemented")
}
func (UnimplementedRouterServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedRouterServiceServer) ListPppSecrets(context.Context, *ListPppSecretsRequest) (*ListPppSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPppSecrets not implemented")
}
func (UnimplementedRouterServiceServer) GetPppSecret(context.Context, *GetPppSecretRequest) (*GetPppSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPppSecret not implemented")
}
func (UnimplementedRouterServiceServer) AddPppSecret(context.Context, *AddPppSecretRequest) (*AddPppSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPppSecret not implemented")
}
func (UnimplementedRouterServiceServer) UpdatePppSecret(context.Context, *UpdatePppSecretRequest) (*UpdatePppSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePppSecret not implemented")
}
func (UnimplementedRouterServiceServer) DeletePppSecret(context.Context, *DeletePppSecretRequest) (*DeletePppSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePppSecret not implemented")
}
func (UnimplementedRouterServiceServer) EnablePppSecret(context.Context, *EnablePppSecretRequest) (*EnablePppSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnablePppSecret not implemented")
}
func (UnimplementedRouterServiceServer) DisablePppSecret(context.Context, *DisablePppSecretRequest) (*DisablePppSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisablePppSecret not implemented")
}
func (UnimplementedRouterServiceServer) ListPppProfiles(context.Context, *ListPppProfilesRequest) (*ListPppProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPppProfiles not implemented")
}
func (UnimplementedRouterServiceServer) AddPppProfile(context.Context, *AddPppProfileRequest) (*AddPppProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPppProfile not implemented")
}
func (UnimplementedRouterServiceServer) UpdatePppProfile(context.Context, *UpdatePppProfileRequest) (*UpdatePppProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePppProfile not implemented")
}
func (UnimplementedRouterServiceServer) DeletePppProfile(context.Context, *DeletePppProfileRequest) (*DeletePppProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePppProfile not implemented")
}
func (UnimplementedRouterServiceServer) ListPppActive(context.Context, *ListPppActiveRequest) (*ListPppActiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPppActive not implemented")
}
func (UnimplementedRouterServiceServer) DisconnectPppActive(context.Context, *DisconnectPppActiveRequest) (*DisconnectPppActiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectPppActive not implemented")
}
func (UnimplementedRouterServiceServer) ListPppPools(context.Context, *ListPppPoolsRequest) (*ListPppPoolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPppPools not implemented")
}
func (UnimplementedRouterServiceServer) mustEmbedUnimplementedRouterServiceServer() {}
func (UnimplementedRouterServiceServer) testEmbeddedByValue()                       {}

// UnsafeRouterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouterServiceServer will
// result in compilation errors.
type UnsafeRouterServiceServer interface {
	mustEmbedUnimplementedRouterServiceServer()
}

func RegisterRouterServiceServer(s grpc.ServiceRegistrar, srv RouterServiceServer) {
	// If the following call panics, it indicates UnimplementedRouterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouterService_ServiceDesc, srv)
}

func _RouterService_TestConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).TestConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_TestConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).TestConnect(ctx, req.(*TestConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_GetDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetDashboard(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListActiveHotspotUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListActiveHotspotUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_ListActiveHotspotUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListActiveHotspotUsers(ctx, req.(*ListActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListHotspotUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHotspotUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListHotspotUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_ListHotspotUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListHotspotUsers(ctx, req.(*ListHotspotUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_AddHotspotUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHotspotUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).AddHotspotUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_AddHotspotUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).AddHotspotUser(ctx, req.(*AddHotspotUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_RemoveHotspotUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveHotspotUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).RemoveHotspotUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_RemoveHotspotUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).RemoveHotspotUser(ctx, req.(*RemoveHotspotUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListHotspotProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListHotspotProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_ListHotspotProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListHotspotProfiles(ctx, req.(*ListProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetHotspotProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetHotspotProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_GetHotspotProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetHotspotProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetSystemResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetSystemResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_GetSystemResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetSystemResource(ctx, req.(*SystemResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_GetInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetInterfaces(ctx, req.(*InterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_UpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).UpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_UpdateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).UpdateSession(ctx, req.(*UpdateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListPppSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPppSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListPppSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_ListPppSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListPppSecrets(ctx, req.(*ListPppSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetPppSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPppSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetPppSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_GetPppSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetPppSecret(ctx, req.(*GetPppSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_AddPppSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPppSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).AddPppSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_AddPppSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).AddPppSecret(ctx, req.(*AddPppSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_UpdatePppSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePppSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).UpdatePppSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_UpdatePppSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).UpdatePppSecret(ctx, req.(*UpdatePppSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_DeletePppSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePppSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).DeletePppSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_DeletePppSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).DeletePppSecret(ctx, req.(*DeletePppSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_EnablePppSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnablePppSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).EnablePppSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_EnablePppSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).EnablePppSecret(ctx, req.(*EnablePppSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_DisablePppSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisablePppSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).DisablePppSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_DisablePppSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).DisablePppSecret(ctx, req.(*DisablePppSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListPppProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPppProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListPppProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_ListPppProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListPppProfiles(ctx, req.(*ListPppProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_AddPppProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPppProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).AddPppProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_AddPppProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).AddPppProfile(ctx, req.(*AddPppProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_UpdatePppProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePppProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).UpdatePppProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_UpdatePppProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).UpdatePppProfile(ctx, req.(*UpdatePppProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_DeletePppProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePppProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).DeletePppProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_DeletePppProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).DeletePppProfile(ctx, req.(*DeletePppProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListPppActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPppActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListPppActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_ListPppActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListPppActive(ctx, req.(*ListPppActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_DisconnectPppActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectPppActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).DisconnectPppActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_DisconnectPppActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).DisconnectPppActive(ctx, req.(*DisconnectPppActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ListPppPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPppPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ListPppPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_ListPppPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ListPppPools(ctx, req.(*ListPppPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RouterService_ServiceDesc is the grpc.ServiceDesc for RouterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "router.RouterService",
	HandlerType: (*RouterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestConnect",
			Handler:    _RouterService_TestConnect_Handler,
		},
		{
			MethodName: "GetDashboard",
			Handler:    _RouterService_GetDashboard_Handler,
		},
		{
			MethodName: "ListActiveHotspotUsers",
			Handler:    _RouterService_ListActiveHotspotUsers_Handler,
		},
		{
			MethodName: "ListHotspotUsers",
			Handler:    _RouterService_ListHotspotUsers_Handler,
		},
		{
			MethodName: "AddHotspotUser",
			Handler:    _RouterService_AddHotspotUser_Handler,
		},
		{
			MethodName: "RemoveHotspotUser",
			Handler:    _RouterService_RemoveHotspotUser_Handler,
		},
		{
			MethodName: "ListHotspotProfiles",
			Handler:    _RouterService_ListHotspotProfiles_Handler,
		},
		{
			MethodName: "GetHotspotProfile",
			Handler:    _RouterService_GetHotspotProfile_Handler,
		},
		{
			MethodName: "GetSystemResource",
			Handler:    _RouterService_GetSystemResource_Handler,
		},
		{
			MethodName: "GetInterfaces",
			Handler:    _RouterService_GetInterfaces_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _RouterService_ListSessions_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _RouterService_GetSession_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _RouterService_CreateSession_Handler,
		},
		{
			MethodName: "UpdateSession",
			Handler:    _RouterService_UpdateSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _RouterService_DeleteSession_Handler,
		},
		{
			MethodName: "ListPppSecrets",
			Handler:    _RouterService_ListPppSecrets_Handler,
		},
		{
			MethodName: "GetPppSecret",
			Handler:    _RouterService_GetPppSecret_Handler,
		},
		{
			MethodName: "AddPppSecret",
			Handler:    _RouterService_AddPppSecret_Handler,
		},
		{
			MethodName: "UpdatePppSecret",
			Handler:    _RouterService_UpdatePppSecret_Handler,
		},
		{
			MethodName: "DeletePppSecret",
			Handler:    _RouterService_DeletePppSecret_Handler,
		},
		{
			MethodName: "EnablePppSecret",
			Handler:    _RouterService_EnablePppSecret_Handler,
		},
		{
			MethodName: "DisablePppSecret",
			Handler:    _RouterService_DisablePppSecret_Handler,
		},
		{
			MethodName: "ListPppProfiles",
			Handler:    _RouterService_ListPppProfiles_Handler,
		},
		{
			MethodName: "AddPppProfile",
			Handler:    _RouterService_AddPppProfile_Handler,
		},
		{
			MethodName: "UpdatePppProfile",
			Handler:    _RouterService_UpdatePppProfile_Handler,
		},
		{
			MethodName: "DeletePppProfile",
			Handler:    _RouterService_DeletePppProfile_Handler,
		},
		{
			MethodName: "ListPppActive",
			Handler:    _RouterService_ListPppActive_Handler,
		},
		{
			MethodName: "DisconnectPppActive",
			Handler:    _RouterService_DisconnectPppActive_Handler,
		},
		{
			MethodName: "ListPppPools",
			Handler:    _RouterService_ListPppPools_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/router.proto",
}
