// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/router.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ── Connection test ────────────────────────────────────────────────
type TestConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectRequest) Reset() {
	*x = TestConnectRequest{}
	mi := &file_proto_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectRequest) ProtoMessage() {}

func (x *TestConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectRequest.ProtoReflect.Descriptor instead.
func (*TestConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{0}
}

func (x *TestConnectRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type TestConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	RosVersion    string                 `protobuf:"bytes,3,opt,name=ros_version,json=rosVersion,proto3" json:"ros_version,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectResponse) Reset() {
	*x = TestConnectResponse{}
	mi := &file_proto_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectResponse) ProtoMessage() {}

func (x *TestConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectResponse.ProtoReflect.Descriptor instead.
func (*TestConnectResponse) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{1}
}

func (x *TestConnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestConnectResponse) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *TestConnectResponse) GetRosVersion() string {
	if x != nil {
		return x.RosVersion
	}
	return ""
}

func (x *TestConnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ── Dashboard ─────────────────────────────────────────────────────
type GetDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_proto_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{2}
}

func (x *GetDashboardRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetDashboardResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error              string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Identity           string                 `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	RosVersion         string                 `protobuf:"bytes,4,opt,name=ros_version,json=rosVersion,proto3" json:"ros_version,omitempty"`
	Uptime             string                 `protobuf:"bytes,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Version            string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	CpuLoad            string                 `protobuf:"bytes,7,opt,name=cpu_load,json=cpuLoad,proto3" json:"cpu_load,omitempty"`
	FreeMemory         string                 `protobuf:"bytes,8,opt,name=free_memory,json=freeMemory,proto3" json:"free_memory,omitempty"`
	TotalMemory        string                 `protobuf:"bytes,9,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	FreeHdd            string                 `protobuf:"bytes,10,opt,name=free_hdd,json=freeHdd,proto3" json:"free_hdd,omitempty"`
	TotalHdd           string                 `protobuf:"bytes,11,opt,name=total_hdd,json=totalHdd,proto3" json:"total_hdd,omitempty"`
	ActiveHotspotUsers int32                  `protobuf:"varint,12,opt,name=active_hotspot_users,json=activeHotspotUsers,proto3" json:"active_hotspot_users,omitempty"`
	TotalHotspotUsers  int32                  `protobuf:"varint,13,opt,name=total_hotspot_users,json=totalHotspotUsers,proto3" json:"total_hotspot_users,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetDashboardResponse) Reset() {
	*x = GetDashboardResponse{}
	mi := &file_proto_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardResponse) ProtoMessage() {}

func (x *GetDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{3}
}

func (x *GetDashboardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetDashboardResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetDashboardResponse) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *GetDashboardResponse) GetRosVersion() string {
	if x != nil {
		return x.RosVersion
	}
	return ""
}

func (x *GetDashboardResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *GetDashboardResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetDashboardResponse) GetCpuLoad() string {
	if x != nil {
		return x.CpuLoad
	}
	return ""
}

func (x *GetDashboardResponse) GetFreeMemory() string {
	if x != nil {
		return x.FreeMemory
	}
	return ""
}

func (x *GetDashboardResponse) GetTotalMemory() string {
	if x != nil {
		return x.TotalMemory
	}
	return ""
}

func (x *GetDashboardResponse) GetFreeHdd() string {
	if x != nil {
		return x.FreeHdd
	}
	return ""
}

func (x *GetDashboardResponse) GetTotalHdd() string {
	if x != nil {
		return x.TotalHdd
	}
	return ""
}

func (x *GetDashboardResponse) GetActiveHotspotUsers() int32 {
	if x != nil {
		return x.ActiveHotspotUsers
	}
	return 0
}

func (x *GetDashboardResponse) GetTotalHotspotUsers() int32 {
	if x != nil {
		return x.TotalHotspotUsers
	}
	return 0
}

// ── Hotspot active ────────────────────────────────────────────────
type ListActiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Server        string                 `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveRequest) Reset() {
	*x = ListActiveRequest{}
	mi := &file_proto_router_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveRequest) ProtoMessage() {}

func (x *ListActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveRequest.ProtoReflect.Descriptor instead.
func (*ListActiveRequest) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{4}
}

func (x *ListActiveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListActiveRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

type ActiveHotspotUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	MacAddress    string                 `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Uptime        string                 `protobuf:"bytes,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	BytesIn       string                 `protobuf:"bytes,6,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut      string                 `protobuf:"bytes,7,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	PacketsIn     string                 `protobuf:"bytes,8,opt,name=packets_in,json=packetsIn,proto3" json:"packets_in,omitempty"`
	PacketsOut    string                 `protobuf:"bytes,9,opt,name=packets_out,json=packetsOut,proto3" json:"packets_out,omitempty"`
	Server        string                 `protobuf:"bytes,10,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveHotspotUser) Reset() {
	*x = ActiveHotspotUser{}
	mi := &file_proto_router_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveHotspotUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveHotspotUser) ProtoMessage() {}

func (x *ActiveHotspotUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveHotspotUser.ProtoReflect.Descriptor instead.
func (*ActiveHotspotUser) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{5}
}

func (x *ActiveHotspotUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActiveHotspotUser) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ActiveHotspotUser) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ActiveHotspotUser) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *ActiveHotspotUser) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *ActiveHotspotUser) GetBytesIn() string {
	if x != nil {
		return x.BytesIn
	}
	return ""
}

func (x *ActiveHotspotUser) GetBytesOut() string {
	if x != nil {
		return x.BytesOut
	}
	return ""
}

func (x *ActiveHotspotUser) GetPacketsIn() string {
	if x != nil {
		return x.PacketsIn
	}
	return ""
}

func (x *ActiveHotspotUser) GetPacketsOut() string {
	if x != nil {
		return x.PacketsOut
	}
	return ""
}

func (x *ActiveHotspotUser) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

type ListActiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Users         []*ActiveHotspotUser   `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveResponse) Reset() {
	*x = ListActiveResponse{}
	mi := &file_proto_router_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveResponse) ProtoMessage() {}

func (x *ListActiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveResponse.ProtoReflect.Descriptor instead.
func (*ListActiveResponse) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{6}
}

func (x *ListActiveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListActiveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListActiveResponse) GetUsers() []*ActiveHotspotUser {
	if x != nil {
		return x.Users
	}
	return nil
}

// ── Hotspot users ─────────────────────────────────────────────────
type ListHotspotUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Profile       string                 `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHotspotUsersRequest) Reset() {
	*x = ListHotspotUsersRequest{}
	mi := &file_proto_router_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHotspotUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHotspotUsersRequest) ProtoMessage() {}

func (x *ListHotspotUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHotspotUsersRequest.ProtoReflect.Descriptor instead.
func (*ListHotspotUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{7}
}

func (x *ListHotspotUsersRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListHotspotUsersRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *ListHotspotUsersRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type HotspotUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Profile       string                 `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	LimitUptime   string                 `protobuf:"bytes,6,opt,name=limit_uptime,json=limitUptime,proto3" json:"limit_uptime,omitempty"`
	Disabled      string                 `protobuf:"bytes,7,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotspotUser) Reset() {
	*x = HotspotUser{}
	mi := &file_proto_router_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotspotUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotspotUser) ProtoMessage() {}

func (x *HotspotUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotspotUser.ProtoReflect.Descriptor instead.
func (*HotspotUser) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{8}
}

func (x *HotspotUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HotspotUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HotspotUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *HotspotUser) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *HotspotUser) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *HotspotUser) GetLimitUptime() string {
	if x != nil {
		return x.LimitUptime
	}
	return ""
}

func (x *HotspotUser) GetDisabled() string {
	if x != nil {
		return x.Disabled
	}
	return ""
}

type ListHotspotUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Users         []*HotspotUser         `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHotspotUsersResponse) Reset() {
	*x = ListHotspotUsersResponse{}
	mi := &file_proto_router_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHotspotUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHotspotUsersResponse) ProtoMessage() {}

func (x *ListHotspotUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHotspotUsersResponse.ProtoReflect.Descriptor instead.
func (*ListHotspotUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{9}
}

func (x *ListHotspotUsersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListHotspotUsersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListHotspotUsersResponse) GetUsers() []*HotspotUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type AddHotspotUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Profile       string                 `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	LimitUptime   string                 `protobuf:"bytes,6,opt,name=limit_uptime,json=limitUptime,proto3" json:"limit_uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHotspotUserRequest) Reset() {
	*x = AddHotspotUserRequest{}
	mi := &file_proto_router_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHotspotUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHotspotUserRequest) ProtoMessage() {}

func (x *AddHotspotUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHotspotUserRequest.ProtoReflect.Descriptor instead.
func (*AddHotspotUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{10}
}

func (x *AddHotspotUserRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddHotspotUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddHotspotUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AddHotspotUserRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *AddHotspotUserRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AddHotspotUserRequest) GetLimitUptime() string {
	if x != nil {
		return x.LimitUptime
	}
	return ""
}

type AddHotspotUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHotspotUserResponse) Reset() {
	*x = AddHotspotUserResponse{}
	mi := &file_proto_router_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHotspotUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHotspotUserResponse) ProtoMessage() {}

func (x *AddHotspotUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHotspotUserResponse.ProtoReflect.Descriptor instead.
func (*AddHotspotUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{11}
}

func (x *AddHotspotUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddHotspotUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RemoveHotspotUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveHotspotUserRequest) Reset() {
	*x = RemoveHotspotUserRequest{}
	mi := &file_proto_router_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveHotspotUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveHotspotUserRequest) ProtoMessage() {}

func (x *RemoveHotspotUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveHotspotUserRequest.ProtoReflect.Descriptor instead.
func (*RemoveHotspotUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveHotspotUserRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RemoveHotspotUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveHotspotUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveHotspotUserResponse) Reset() {
	*x = RemoveHotspotUserResponse{}
	mi := &file_proto_router_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveHotspotUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveHotspotUserResponse) ProtoMessage() {}

func (x *RemoveHotspotUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveHotspotUserResponse.ProtoReflect.Descriptor instead.
func (*RemoveHotspotUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveHotspotUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveHotspotUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ── Hotspot profiles ──────────────────────────────────────────────
type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_proto_router_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{14}
}

func (x *ListProfilesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type HotspotProfile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OnLogin        string                 `protobuf:"bytes,3,opt,name=on_login,json=onLogin,proto3" json:"on_login,omitempty"`
	SessionTimeout string                 `protobuf:"bytes,4,opt,name=session_timeout,json=sessionTimeout,proto3" json:"session_timeout,omitempty"`
	IdleTimeout    string                 `protobuf:"bytes,5,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	RateLimit      string                 `protobuf:"bytes,6,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	SharedUsers    string                 `protobuf:"bytes,7,opt,name=shared_users,json=sharedUsers,proto3" json:"shared_users,omitempty"`
	AddressPool    string                 `protobuf:"bytes,8,opt,name=address_pool,json=addressPool,proto3" json:"address_pool,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HotspotProfile) Reset() {
	*x = HotspotProfile{}
	mi := &file_proto_router_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotspotProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotspotProfile) ProtoMessage() {}

func (x *HotspotProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotspotProfile.ProtoReflect.Descriptor instead.
func (*HotspotProfile) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{15}
}

func (x *HotspotProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HotspotProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HotspotProfile) GetOnLogin() string {
	if x != nil {
		return x.OnLogin
	}
	return ""
}

func (x *HotspotProfile) GetSessionTimeout() string {
	if x != nil {
		return x.SessionTimeout
	}
	return ""
}

func (x *HotspotProfile) GetIdleTimeout() string {
	if x != nil {
		return x.IdleTimeout
	}
	return ""
}

func (x *HotspotProfile) GetRateLimit() string {
	if x != nil {
		return x.RateLimit
	}
	return ""
}

func (x *HotspotProfile) GetSharedUsers() string {
	if x != nil {
		return x.SharedUsers
	}
	return ""
}

func (x *HotspotProfile) GetAddressPool() string {
	if x != nil {
		return x.AddressPool
	}
	return ""
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Profiles      []*HotspotProfile      `protobuf:"bytes,3,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_proto_router_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{16}
}

func (x *ListProfilesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListProfilesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListProfilesResponse) GetProfiles() []*HotspotProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_proto_router_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{17}
}

func (x *GetProfileRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Profile       *HotspotProfile        `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_proto_router_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{18}
}

func (x *GetProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetProfileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetProfileResponse) GetProfile() *HotspotProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// ── System ────────────────────────────────────────────────────────
type SystemResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemResourceRequest) Reset() {
	*x = SystemResourceRequest{}
	mi := &file_proto_router_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemResourceRequest) ProtoMessage() {}

func (x *SystemResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemResourceRequest.ProtoReflect.Descriptor instead.
func (*SystemResourceRequest) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{19}
}

func (x *SystemResourceRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SystemResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Uptime        string                 `protobuf:"bytes,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	CpuLoad       string                 `protobuf:"bytes,5,opt,name=cpu_load,json=cpuLoad,proto3" json:"cpu_load,omitempty"`
	FreeMemory    string                 `protobuf:"bytes,6,opt,name=free_memory,json=freeMemory,proto3" json:"free_memory,omitempty"`
	TotalMemory   string                 `protobuf:"bytes,7,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	FreeHdd       string                 `protobuf:"bytes,8,opt,name=free_hdd,json=freeHdd,proto3" json:"free_hdd,omitempty"`
	TotalHdd      string                 `protobuf:"bytes,9,opt,name=total_hdd,json=totalHdd,proto3" json:"total_hdd,omitempty"`
	RosVersion    string                 `protobuf:"bytes,10,opt,name=ros_version,json=rosVersion,proto3" json:"ros_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemResourceResponse) Reset() {
	*x = SystemResourceResponse{}
	mi := &file_proto_router_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemResourceResponse) ProtoMessage() {}

func (x *SystemResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemResourceResponse.ProtoReflect.Descriptor instead.
func (*SystemResourceResponse) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{20}
}

func (x *SystemResourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SystemResourceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SystemResourceResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SystemResourceResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *SystemResourceResponse) GetCpuLoad() string {
	if x != nil {
		return x.CpuLoad
	}
	return ""
}

func (x *SystemResourceResponse) GetFreeMemory() string {
	if x != nil {
		return x.FreeMemory
	}
	return ""
}

func (x *SystemResourceResponse) GetTotalMemory() string {
	if x != nil {
		return x.TotalMemory
	}
	return ""
}

func (x *SystemResourceResponse) GetFreeHdd() string {
	if x != nil {
		return x.FreeHdd
	}
	return ""
}

func (x *SystemResourceResponse) GetTotalHdd() string {
	if x != nil {
		return x.TotalHdd
	}
	return ""
}

func (x *SystemResourceResponse) GetRosVersion() string {
	if x != nil {
		return x.RosVersion
	}
	return ""
}

type InterfacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfacesRequest) Reset() {
	*x = InterfacesRequest{}
	mi := &file_proto_router_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfacesRequest) ProtoMessage() {}

func (x *InterfacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfacesRequest.ProtoReflect.Descriptor instead.
func (*InterfacesRequest) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{21}
}

func (x *InterfacesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type InterfaceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	MacAddress    string                 `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Tx            string                 `protobuf:"bytes,5,opt,name=tx,proto3" json:"tx,omitempty"`
	Rx            string                 `protobuf:"bytes,6,opt,name=rx,proto3" json:"rx,omitempty"`
	Running       string                 `protobuf:"bytes,7,opt,name=running,proto3" json:"running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceInfo) Reset() {
	*x = InterfaceInfo{}
	mi := &file_proto_router_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceInfo) ProtoMessage() {}

func (x *InterfaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceInfo.ProtoReflect.Descriptor instead.
func (*InterfaceInfo) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{22}
}

func (x *InterfaceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InterfaceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InterfaceInfo) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *InterfaceInfo) GetTx() string {
	if x != nil {
		return x.Tx
	}
	return ""
}

func (x *InterfaceInfo) GetRx() string {
	if x != nil {
		return x.Rx
	}
	return ""
}

func (x *InterfaceInfo) GetRunning() string {
	if x != nil {
		return x.Running
	}
	return ""
}

type InterfacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Interfaces    []*InterfaceInfo       `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfacesResponse) Reset() {
	*x = InterfacesResponse{}
	mi := &file_proto_router_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfacesResponse) ProtoMessage() {}

func (x *InterfacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfacesResponse.ProtoReflect.Descriptor instead.
func (*InterfacesResponse) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{23}
}

func (x *InterfacesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InterfacesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *InterfacesResponse) GetInterfaces() []*InterfaceInfo {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

var File_proto_router_proto protoreflect.FileDescriptor

const file_proto_router_proto_rawDesc = "" +
	"\n" +
	"\x12proto/router.proto\x12\x06router\"3\n" +
	"\x12TestConnectRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x82\x01\n" +
	"\x13TestConnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12\x1f\n" +
	"\vros_version\x18\x03 \x01(\tR\n" +
	"rosVersion\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"4\n" +
	"\x13GetDashboardRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xae\x03\n" +
	"\x14GetDashboardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1a\n" +
	"\bidentity\x18\x03 \x01(\tR\bidentity\x12\x1f\n" +
	"\vros_version\x18\x04 \x01(\tR\n" +
	"rosVersion\x12\x16\n" +
	"\x06uptime\x18\x05 \x01(\tR\x06uptime\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x19\n" +
	"\bcpu_load\x18\a \x01(\tR\acpuLoad\x12\x1f\n" +
	"\vfree_memory\x18\b \x01(\tR\n" +
	"freeMemory\x12!\n" +
	"\ftotal_memory\x18\t \x01(\tR\vtotalMemory\x12\x19\n" +
	"\bfree_hdd\x18\n" +
	" \x01(\tR\afreeHdd\x12\x1b\n" +
	"\ttotal_hdd\x18\v \x01(\tR\btotalHdd\x120\n" +
	"\x14active_hotspot_users\x18\f \x01(\x05R\x12activeHotspotUsers\x12.\n" +
	"\x13total_hotspot_users\x18\r \x01(\x05R\x11totalHotspotUsers\"J\n" +
	"\x11ListActiveRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06server\x18\x02 \x01(\tR\x06server\"\x9a\x02\n" +
	"\x11ActiveHotspotUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1f\n" +
	"\vmac_address\x18\x04 \x01(\tR\n" +
	"macAddress\x12\x16\n" +
	"\x06uptime\x18\x05 \x01(\tR\x06uptime\x12\x19\n" +
	"\bbytes_in\x18\x06 \x01(\tR\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\a \x01(\tR\bbytesOut\x12\x1d\n" +
	"\n" +
	"packets_in\x18\b \x01(\tR\tpacketsIn\x12\x1f\n" +
	"\vpackets_out\x18\t \x01(\tR\n" +
	"packetsOut\x12\x16\n" +
	"\x06server\x18\n" +
	" \x01(\tR\x06server\"u\n" +
	"\x12ListActiveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12/\n" +
	"\x05users\x18\x03 \x03(\v2\x19.router.ActiveHotspotUserR\x05users\"l\n" +
	"\x17ListHotspotUsersRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"\xc0\x01\n" +
	"\vHotspotUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x18\n" +
	"\aprofile\x18\x04 \x01(\tR\aprofile\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12!\n" +
	"\flimit_uptime\x18\x06 \x01(\tR\vlimitUptime\x12\x1a\n" +
	"\bdisabled\x18\a \x01(\tR\bdisabled\"u\n" +
	"\x18ListHotspotUsersResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12)\n" +
	"\x05users\x18\x03 \x03(\v2\x13.router.HotspotUserR\x05users\"\xbd\x01\n" +
	"\x15AddHotspotUserRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x18\n" +
	"\aprofile\x18\x04 \x01(\tR\aprofile\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12!\n" +
	"\flimit_uptime\x18\x06 \x01(\tR\vlimitUptime\"H\n" +
	"\x16AddHotspotUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"M\n" +
	"\x18RemoveHotspotUserRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"K\n" +
	"\x19RemoveHotspotUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"4\n" +
	"\x13ListProfilesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x80\x02\n" +
	"\x0eHotspotProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bon_login\x18\x03 \x01(\tR\aonLogin\x12'\n" +
	"\x0fsession_timeout\x18\x04 \x01(\tR\x0esessionTimeout\x12!\n" +
	"\fidle_timeout\x18\x05 \x01(\tR\vidleTimeout\x12\x1d\n" +
	"\n" +
	"rate_limit\x18\x06 \x01(\tR\trateLimit\x12!\n" +
	"\fshared_users\x18\a \x01(\tR\vsharedUsers\x12!\n" +
	"\faddress_pool\x18\b \x01(\tR\vaddressPool\"z\n" +
	"\x14ListProfilesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x122\n" +
	"\bprofiles\x18\x03 \x03(\v2\x16.router.HotspotProfileR\bprofiles\"F\n" +
	"\x11GetProfileRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"v\n" +
	"\x12GetProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x120\n" +
	"\aprofile\x18\x03 \x01(\v2\x16.router.HotspotProfileR\aprofile\"6\n" +
	"\x15SystemResourceRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xb2\x02\n" +
	"\x16SystemResourceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\tR\x06uptime\x12\x19\n" +
	"\bcpu_load\x18\x05 \x01(\tR\acpuLoad\x12\x1f\n" +
	"\vfree_memory\x18\x06 \x01(\tR\n" +
	"freeMemory\x12!\n" +
	"\ftotal_memory\x18\a \x01(\tR\vtotalMemory\x12\x19\n" +
	"\bfree_hdd\x18\b \x01(\tR\afreeHdd\x12\x1b\n" +
	"\ttotal_hdd\x18\t \x01(\tR\btotalHdd\x12\x1f\n" +
	"\vros_version\x18\n" +
	" \x01(\tR\n" +
	"rosVersion\"2\n" +
	"\x11InterfacesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xa2\x01\n" +
	"\rInterfaceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1f\n" +
	"\vmac_address\x18\x04 \x01(\tR\n" +
	"macAddress\x12\x0e\n" +
	"\x02tx\x18\x05 \x01(\tR\x02tx\x12\x0e\n" +
	"\x02rx\x18\x06 \x01(\tR\x02rx\x12\x18\n" +
	"\arunning\x18\a \x01(\tR\arunning\"{\n" +
	"\x12InterfacesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x125\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\v2\x15.router.InterfaceInfoR\n" +
	"interfaces2\xaf\x06\n" +
	"\rRouterService\x12F\n" +
	"\vTestConnect\x12\x1a.router.TestConnectRequest\x1a\x1b.router.TestConnectResponse\x12I\n" +
	"\fGetDashboard\x12\x1b.router.GetDashboardRequest\x1a\x1c.router.GetDashboardResponse\x12O\n" +
	"\x16ListActiveHotspotUsers\x12\x19.router.ListActiveRequest\x1a\x1a.router.ListActiveResponse\x12U\n" +
	"\x10ListHotspotUsers\x12\x1f.router.ListHotspotUsersRequest\x1a .router.ListHotspotUsersResponse\x12O\n" +
	"\x0eAddHotspotUser\x12\x1d.router.AddHotspotUserRequest\x1a\x1e.router.AddHotspotUserResponse\x12X\n" +
	"\x11RemoveHotspotUser\x12 .router.RemoveHotspotUserRequest\x1a!.router.RemoveHotspotUserResponse\x12P\n" +
	"\x13ListHotspotProfiles\x12\x1b.router.ListProfilesRequest\x1a\x1c.router.ListProfilesResponse\x12J\n" +
	"\x11GetHotspotProfile\x12\x19.router.GetProfileRequest\x1a\x1a.router.GetProfileResponse\x12R\n" +
	"\x11GetSystemResource\x12\x1d.router.SystemResourceRequest\x1a\x1e.router.SystemResourceResponse\x12F\n" +
	"\rGetInterfaces\x12\x19.router.InterfacesRequest\x1a\x1a.router.InterfacesResponseB.Z,github.com/mikhmon/mikrotik-go-service/protob\x06proto3"

var (
	file_proto_router_proto_rawDescOnce sync.Once
	file_proto_router_proto_rawDescData []byte
)

func file_proto_router_proto_rawDescGZIP() []byte {
	file_proto_router_proto_rawDescOnce.Do(func() {
		file_proto_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_router_proto_rawDesc), len(file_proto_router_proto_rawDesc)))
	})
	return file_proto_router_proto_rawDescData
}

var file_proto_router_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_router_proto_goTypes = []any{
	(*TestConnectRequest)(nil),        // 0: router.TestConnectRequest
	(*TestConnectResponse)(nil),       // 1: router.TestConnectResponse
	(*GetDashboardRequest)(nil),       // 2: router.GetDashboardRequest
	(*GetDashboardResponse)(nil),      // 3: router.GetDashboardResponse
	(*ListActiveRequest)(nil),         // 4: router.ListActiveRequest
	(*ActiveHotspotUser)(nil),         // 5: router.ActiveHotspotUser
	(*ListActiveResponse)(nil),        // 6: router.ListActiveResponse
	(*ListHotspotUsersRequest)(nil),   // 7: router.ListHotspotUsersRequest
	(*HotspotUser)(nil),               // 8: router.HotspotUser
	(*ListHotspotUsersResponse)(nil),  // 9: router.ListHotspotUsersResponse
	(*AddHotspotUserRequest)(nil),     // 10: router.AddHotspotUserRequest
	(*AddHotspotUserResponse)(nil),    // 11: router.AddHotspotUserResponse
	(*RemoveHotspotUserRequest)(nil),  // 12: router.RemoveHotspotUserRequest
	(*RemoveHotspotUserResponse)(nil), // 13: router.RemoveHotspotUserResponse
	(*ListProfilesRequest)(nil),       // 14: router.ListProfilesRequest
	(*HotspotProfile)(nil),            // 15: router.HotspotProfile
	(*ListProfilesResponse)(nil),      // 16: router.ListProfilesResponse
	(*GetProfileRequest)(nil),         // 17: router.GetProfileRequest
	(*GetProfileResponse)(nil),        // 18: router.GetProfileResponse
	(*SystemResourceRequest)(nil),     // 19: router.SystemResourceRequest
	(*SystemResourceResponse)(nil),    // 20: router.SystemResourceResponse
	(*InterfacesRequest)(nil),         // 21: router.InterfacesRequest
	(*InterfaceInfo)(nil),             // 22: router.InterfaceInfo
	(*InterfacesResponse)(nil),        // 23: router.InterfacesResponse
}
var file_proto_router_proto_depIdxs = []int32{
	5,  // 0: router.ListActiveResponse.users:type_name -> router.ActiveHotspotUser
	8,  // 1: router.ListHotspotUsersResponse.users:type_name -> router.HotspotUser
	15, // 2: router.ListProfilesResponse.profiles:type_name -> router.HotspotProfile
	15, // 3: router.GetProfileResponse.profile:type_name -> router.HotspotProfile
	22, // 4: router.InterfacesResponse.interfaces:type_name -> router.InterfaceInfo
	0,  // 5: router.RouterService.TestConnect:input_type -> router.TestConnectRequest
	2,  // 6: router.RouterService.GetDashboard:input_type -> router.GetDashboardRequest
	4,  // 7: router.RouterService.ListActiveHotspotUsers:input_type -> router.ListActiveRequest
	7,  // 8: router.RouterService.ListHotspotUsers:input_type -> router.ListHotspotUsersRequest
	10, // 9: router.RouterService.AddHotspotUser:input_type -> router.AddHotspotUserRequest
	12, // 10: router.RouterService.RemoveHotspotUser:input_type -> router.RemoveHotspotUserRequest
	14, // 11: router.RouterService.ListHotspotProfiles:input_type -> router.ListProfilesRequest
	17, // 12: router.RouterService.GetHotspotProfile:input_type -> router.GetProfileRequest
	19, // 13: router.RouterService.GetSystemResource:input_type -> router.SystemResourceRequest
	21, // 14: router.RouterService.GetInterfaces:input_type -> router.InterfacesRequest
	1,  // 15: router.RouterService.TestConnect:output_type -> router.TestConnectResponse
	3,  // 16: router.RouterService.GetDashboard:output_type -> router.GetDashboardResponse
	6,  // 17: router.RouterService.ListActiveHotspotUsers:output_type -> router.ListActiveResponse
	9,  // 18: router.RouterService.ListHotspotUsers:output_type -> router.ListHotspotUsersResponse
	11, // 19: router.RouterService.AddHotspotUser:output_type -> router.AddHotspotUserResponse
	13, // 20: router.RouterService.RemoveHotspotUser:output_type -> router.RemoveHotspotUserResponse
	16, // 21: router.RouterService.ListHotspotProfiles:output_type -> router.ListProfilesResponse
	18, // 22: router.RouterService.GetHotspotProfile:output_type -> router.GetProfileResponse
	20, // 23: router.RouterService.GetSystemResource:output_type -> router.SystemResourceResponse
	23, // 24: router.RouterService.GetInterfaces:output_type -> router.InterfacesResponse
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_router_proto_init() }
func file_proto_router_proto_init() {
	if File_proto_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_router_proto_rawDesc), len(file_proto_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_router_proto_goTypes,
		DependencyIndexes: file_proto_router_proto_depIdxs,
		MessageInfos:      file_proto_router_proto_msgTypes,
	}.Build()
	File_proto_router_proto = out.File
	file_proto_router_proto_goTypes = nil
	file_proto_router_proto_depIdxs = nil
}
