import { Injectable, Logger, OnModuleDestroy, OnModuleInit } from '@nestjs/common';
import * as grpc from '@grpc/grpc-js';
import * as protoLoader from '@grpc/proto-loader';
import { loadPackageDefinition } from '@grpc/grpc-js';
import { join } from 'path';

@Injectable()
export class MikrotikGrpcClient implements OnModuleInit, OnModuleDestroy {
  private readonly logger = new Logger(MikrotikGrpcClient.name);
  private client: any = null;
  private creds: grpc.ChannelCredentials = grpc.credentials.createInsecure();
  private maxRetries = 6;
  private initialBackoffMs = 500;
  private backoffFactor = 2;
  private maxBackoffMs = 10000;

  private get address(): string { return process.env.MIKROTIK_GRPC_ADDR || 'localhost:50051'; }
  private get protoPath(): string { return process.env.ROUTER_PROTO_PATH || join(__dirname, '..', 'proto', 'router.proto'); }

  onModuleInit() { this.initClientOnce().catch((e) => { this.logger.warn(`[mikrotik-grpc] initial init failed (${e?.message || e}) — will retry on calls`); this.client = null; }); }

  private async initClientOnce(): Promise<void> {
    const packageDef = protoLoader.loadSync(this.protoPath, { keepCase: false, longs: String, enums: String, defaults: true, oneofs: true });
    const proto = loadPackageDefinition(packageDef) as any;
    const svc = proto.router?.RouterService;
    if (!svc) throw new Error('RouterService not found in proto');
    this.client = new svc(this.address, this.creds);
    await new Promise<void>((resolve, reject) => {
      const deadline = new Date(Date.now() + 3000);
      try {
        this.client.waitForReady(deadline, (err: any) => {
          if (err) { try { this.client.close(); } catch (_) {} this.client = null; reject(err); return; }
          this.logger.log(`[mikrotik-grpc] connected to ${this.address}`); resolve();
        });
      } catch (e) { try { this.client.close(); } catch (_) {} this.client = null; reject(e); }
    });
  }

  private sleep(ms: number) { return new Promise((r) => setTimeout(r, ms)); }

  private async ensureClientReady(): Promise<boolean> {
    if (this.client) return new Promise<boolean>((resolve) => {
      const deadline = new Date(Date.now() + 1000);
      try { this.client.waitForReady(deadline, (err: any) => { if (!err) return resolve(true); try { this.client.close(); } catch (_) {} this.client = null; resolve(false); }); }
      catch (_) { try { this.client.close(); } catch (_) {} this.client = null; resolve(false); }
    });
    let backoff = this.initialBackoffMs;
    for (let attempt = 0; attempt < this.maxRetries; attempt++) {
      try { await this.initClientOnce(); return true; }
      catch (e: any) { this.logger.warn(`[mikrotik-grpc] connect attempt #${attempt + 1} to ${this.address} failed: ${e?.message || e}`); if (attempt === this.maxRetries - 1) break; await this.sleep(backoff); backoff = Math.min(backoff * this.backoffFactor, this.maxBackoffMs); }
    }
    return false;
  }

  onModuleDestroy() { if (this.client) { this.client.close(); this.client = null; } }

  testConnect(sessionId: string): Promise<{ success: boolean; identity?: string; error?: string }> { return new Promise((resolve) => { (async () => { const ready = await this.ensureClientReady(); if (!ready) return resolve({ success: false, error: `mikrotik gRPC client not initialized (target ${this.address})` }); const deadline = new Date(); deadline.setSeconds(deadline.getSeconds()+15); this.client.TestConnect({sessionId},{deadline},(err:any,resp:any)=>{ if(err)return resolve({success:false,error:`gRPC TestConnect failed: ${err.message}`}); if(!resp?.success)return resolve({success:false,error:resp?.error||'TestConnect reported failure'}); resolve({success:true,identity:resp.identity}); }); })(); }); }
  listHotspotUsers(params:{sessionId:string;profile?:string;comment?:string}):Promise<{success:boolean;users?:any[];error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+30);this.client.ListHotspotUsers({sessionId:params.sessionId,profile:params.profile||'',comment:params.comment||''},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC ListHotspotUsers failed: ${err.message}`});resolve({success:true,users:resp?.users||[]});});})();});}
  removeHotspotUser(sessionId:string,name:string):Promise<{success:boolean;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.RemoveHotspotUser({sessionId,name},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC RemoveHotspotUser failed: ${err.message}`});if(!resp?.success)return resolve({success:false,error:resp?.error||'RemoveHotspotUser reported failure'});resolve({success:true});});})();});}
  listSessions():Promise<{success:boolean;sessions?:any[];error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.ListSessions({},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC ListSessions failed: ${err.message}`});if(!resp?.success)return resolve({success:false,error:resp?.error||'ListSessions reported failure'});resolve({success:true,sessions:resp.sessions||[]});});})();});}
  getSession(id:string):Promise<{success:boolean;session?:any;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.GetSession({id},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC GetSession failed: ${err.message}`});if(!resp?.success)return resolve({success:false,error:resp?.error||'Session tidak ditemukan'});resolve({success:true,session:resp.session});});})();});}
  createSession(params:Record<string,any>):Promise<{success:boolean;session?:any;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.CreateSession(params,{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC CreateSession failed: ${err.message}`});if(!resp?.success)return resolve({success:false,error:resp?.error||'CreateSession reported failure'});resolve({success:true,session:resp.session});});})();});}
  updateSession(params:Record<string,any>):Promise<{success:boolean;session?:any;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.UpdateSession(params,{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC UpdateSession failed: ${err.message}`});if(!resp?.success)return resolve({success:false,error:resp?.error||'UpdateSession reported failure'});resolve({success:true,session:resp.session});});})();});}
  deleteSession(id:string):Promise<{success:boolean;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.DeleteSession({id},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC DeleteSession failed: ${err.message}`});if(!resp?.success)return resolve({success:false,error:resp?.error||'DeleteSession reported failure'});resolve({success:true});});})();});}
  listSchedulers(sessionId:string):Promise<{success:boolean;schedulers?:any[];error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.ListSchedulers({sessionId},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC ListSchedulers failed: ${err.message}`});if(!resp?.success)return resolve({success:false,error:resp?.error||'ListSchedulers reported failure'});resolve({success:true,schedulers:resp.schedulers||[]});});})();});}

  listHotspotProfiles(sessionId:string):Promise<{success:boolean;profiles?:any[];error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.ListHotspotProfiles({sessionId},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC ListHotspotProfiles failed: ${err.message}`});resolve({success:true,profiles:resp?.profiles||[]});});})();});}
  getHotspotProfile(sessionId:string,name:string):Promise<{success:boolean;profile?:any;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.GetHotspotProfile({sessionId,name},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC GetHotspotProfile failed: ${err.message}`});if(!resp?.success)return resolve({success:false,error:resp?.error||'Profile tidak ditemukan'});resolve({success:true,profile:resp.profile});});})();});}
  addHotspotProfile(params:{sessionId:string;name:string;onLogin?:string;sessionTimeout?:string;idleTimeout?:string;rateLimit?:string;sharedUsers?:string;addressPool?:string}):Promise<{success:boolean;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.AddHotspotProfile({sessionId:params.sessionId,name:params.name,onLogin:params.onLogin||'',sessionTimeout:params.sessionTimeout||'',idleTimeout:params.idleTimeout||'',rateLimit:params.rateLimit||'',sharedUsers:params.sharedUsers||'',addressPool:params.addressPool||''},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC AddHotspotProfile failed: ${err.message}`});resolve({success:!!resp?.success,error:resp?.success?undefined:resp?.error});});})();});}
  updateHotspotProfile(params:{sessionId:string;name:string;onLogin?:string;sessionTimeout?:string;idleTimeout?:string;rateLimit?:string;sharedUsers?:string;addressPool?:string}):Promise<{success:boolean;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.UpdateHotspotProfile({sessionId:params.sessionId,name:params.name,onLogin:params.onLogin||'',sessionTimeout:params.sessionTimeout||'',idleTimeout:params.idleTimeout||'',rateLimit:params.rateLimit||'',sharedUsers:params.sharedUsers||'',addressPool:params.addressPool||''},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC UpdateHotspotProfile failed: ${err.message}`});resolve({success:!!resp?.success,error:resp?.success?undefined:resp?.error});});})();});}
  deleteHotspotProfile(sessionId:string,name:string):Promise<{success:boolean;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.DeleteHotspotProfile({sessionId,name},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC DeleteHotspotProfile failed: ${err.message}`});resolve({success:!!resp?.success,error:resp?.success?undefined:resp?.error});});})();});}
  bulkRemoveHotspotUsers(sessionId:string,names:string[]):Promise<{success:boolean;removed?:number;failedNames?:string[];error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+30);this.client.BulkRemoveHotspotUsers({sessionId,names},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC BulkRemoveHotspotUsers failed: ${err.message}`});resolve({success:!!resp?.success,removed:resp?.removed||0,failedNames:resp?.failedNames||[],error:resp?.error});});})();});}
  setupExpiryScheduler(sessionId:string):Promise<{success:boolean;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.SetupExpiryScheduler({sessionId},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC SetupExpiryScheduler failed: ${err.message}`});resolve({success:!!resp?.success,error:resp?.success?undefined:resp?.error});});})();});}
  getDashboard(sessionId:string):Promise<{success:boolean;error?:string;[k:string]:any}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.GetDashboard({sessionId},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC GetDashboard failed: ${err.message}`});resolve(resp||{success:false,error:'empty response'});});})();});}
  listActiveHotspotUsers(sessionId:string,server:string):Promise<{success:boolean;users?:any[];error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.ListActiveHotspotUsers({sessionId,server},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC ListActiveHotspotUsers failed: ${err.message}`});resolve({success:true,users:resp?.users||[]});});})();});}
  addHotspotUser(params:{sessionId:string;name:string;password:string;profile:string;comment:string;limitUptime:string}):Promise<{success:boolean;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.AddHotspotUser(params,{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC AddHotspotUser failed: ${err.message}`});resolve({success:resp?.success,error:resp?.error});});})();});}
  getSystemResource(sessionId:string):Promise<{success:boolean;error?:string;[k:string]:any}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.GetSystemResource({sessionId},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC GetSystemResource failed: ${err.message}`});resolve(resp||{success:false,error:'empty response'});});})();});}
  getInterfaces(sessionId:string):Promise<{success:boolean;interfaces?:any[];error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.GetInterfaces({sessionId},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC GetInterfaces failed: ${err.message}`});resolve({success:true,interfaces:resp?.interfaces||[]});});})();});}
  listPppSecrets(sessionId:string,profile?:string,name?:string):Promise<{success:boolean;secrets?:any[];error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+30);this.client.ListPppSecrets({sessionId,profile:profile||'',name:name||''},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC ListPppSecrets failed: ${err.message}`});resolve({success:resp?.success,secrets:resp?.secrets||[],error:resp?.error});});})();});}
  getPppSecret(sessionId:string,name:string):Promise<{success:boolean;secret?:any;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.GetPppSecret({sessionId,name},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC GetPppSecret failed: ${err.message}`});resolve({success:resp?.success,secret:resp?.secret,error:resp?.error});});})();});}
  addPppSecret(params:any):Promise<{success:boolean;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.AddPppSecret(params,{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC AddPppSecret failed: ${err.message}`});resolve({success:resp?.success,error:resp?.error});});})();});}
  updatePppSecret(params:any):Promise<{success:boolean;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.UpdatePppSecret(params,{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC UpdatePppSecret failed: ${err.message}`});resolve({success:resp?.success,error:resp?.error});});})();});}
  deletePppSecret(sessionId:string,name:string):Promise<{success:boolean;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.DeletePppSecret({sessionId,name},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC DeletePppSecret failed: ${err.message}`});resolve({success:resp?.success,error:resp?.error});});})();});}
  enablePppSecret(sessionId:string,name:string):Promise<{success:boolean;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.EnablePppSecret({sessionId,name},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC EnablePppSecret failed: ${err.message}`});resolve({success:resp?.success,error:resp?.error});});})();});}
  disablePppSecret(sessionId:string,name:string):Promise<{success:boolean;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.DisablePppSecret({sessionId,name},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC DisablePppSecret failed: ${err.message}`});resolve({success:resp?.success,error:resp?.error});});})();});}
  listPppProfiles(sessionId:string):Promise<{success:boolean;profiles?:any[];error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.ListPppProfiles({sessionId},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC ListPppProfiles failed: ${err.message}`});resolve({success:resp?.success,profiles:resp?.profiles||[],error:resp?.error});});})();});}
  addPppProfile(params:any):Promise<{success:boolean;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.AddPppProfile(params,{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC AddPppProfile failed: ${err.message}`});resolve({success:resp?.success,error:resp?.error});});})();});}
  updatePppProfile(params:any):Promise<{success:boolean;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.UpdatePppProfile(params,{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC UpdatePppProfile failed: ${err.message}`});resolve({success:resp?.success,error:resp?.error});});})();});}
  deletePppProfile(sessionId:string,name:string):Promise<{success:boolean;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.DeletePppProfile({sessionId,name},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC DeletePppProfile failed: ${err.message}`});resolve({success:resp?.success,error:resp?.error});});})();});}
  listPppActive(sessionId:string):Promise<{success:boolean;connections?:any[];error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.ListPppActive({sessionId},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC ListPppActive failed: ${err.message}`});resolve({success:resp?.success,connections:resp?.connections||[],error:resp?.error});});})();});}
  disconnectPppActive(sessionId:string,name:string):Promise<{success:boolean;error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.DisconnectPppActive({sessionId,name},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC DisconnectPppActive failed: ${err.message}`});resolve({success:resp?.success,error:resp?.error});});})();});}
  listPppPools(sessionId:string):Promise<{success:boolean;pools?:any[];error?:string}>{return new Promise((resolve)=>{(async()=>{const ready=await this.ensureClientReady();if(!ready)return resolve({success:false,error:`mikrotik gRPC client not initialized (target ${this.address})`});const deadline=new Date();deadline.setSeconds(deadline.getSeconds()+15);this.client.ListPppPools({sessionId},{deadline},(err:any,resp:any)=>{if(err)return resolve({success:false,error:`gRPC ListPppPools failed: ${err.message}`});resolve({success:resp?.success,pools:resp?.pools||[],error:resp?.error});});})();});}
}
