import { useEffect, useMemo, useState } from 'react';
import { Check, Eye, Pencil, Plus, RefreshCw, Router, Search, Trash2, X } from 'lucide-react';
import { router } from '../api';

type Session = Record<string, any>;
type Form = { id:string; name:string; ip:string; port:string; user:string; password:string; hotspotName:string; dnsName:string; currency:string; reloadInterval:string; iface:string; idleTo:string; livereport:string };
const emptyForm: Form = { id:'', name:'', ip:'', port:'8728', user:'admin', password:'', hotspotName:'', dnsName:'', currency:'IDR', reloadInterval:'0', iface:'', idleTo:'0', livereport:'' };
const toForm = (s: Session): Form => ({ ...emptyForm, id:String(s.id||''), name:String(s.name||''), ip:String(s.ip||''), port:String(s.port??8728), user:String(s.user||''), password:'', hotspotName:String(s.hotspotName||''), dnsName:String(s.dnsName||''), currency:String(s.currency||'IDR'), reloadInterval:String(s.reloadInterval??0), iface:String(s.iface||''), idleTo:String(s.idleTo??0), livereport:String(s.livereport||'') });

export default function RouterSessionsPage() {
  const [rows, setRows] = useState<Session[]>([]); const [query, setQuery] = useState(''); const [selected, setSelected] = useState<Session | null>(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const [form, setForm] = useState<Form>(emptyForm); const [editor, setEditor] = useState(false); const [testing, setTesting] = useState('');
  const load = async () => { setBusy(true); setNotice(''); try { const data = await router.sessions(); const list = Array.isArray(data) ? data : data?.sessions; setRows(Array.isArray(list) ? list : []); } catch (e:any) { setNotice(e?.message || 'Unable to load router sessions.'); } finally { setBusy(false); } };
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => { const q=query.trim().toLowerCase(); if(!q)return rows; return rows.filter(row=>Object.values(row).some(v=>String(v??'').toLowerCase().includes(q))); }, [rows,query]);
  const inspect = async (row: Session) => { const id=String(row.id||''); if(!id){setSelected(row);return;} setBusy(true); setNotice(''); try { setSelected(await router.getSession(id)); } catch { setSelected(row); } finally { setBusy(false); } };
  const openEditor = (row?: Session) => { setForm(row ? toForm(row) : emptyForm); setEditor(true); setSelected(null); setNotice(''); };
  const save = async () => { if(!form.id||!form.name||!form.ip){setNotice('ID, name, dan IP wajib diisi.');return;} setBusy(true); setNotice(''); try { const body:any={...form,port:Number(form.port)||0,reloadInterval:Number(form.reloadInterval)||0,idleTo:Number(form.idleTo)||0}; const result=await router.saveSession(body); setNotice(result?.success?'Router session saved.':'Saved.'); setEditor(false); await load(); } catch(e:any) { setNotice(e?.message||'Unable to save router session.'); } finally { setBusy(false); } };
  const remove = async (id:string) => { if(!window.confirm(`Delete router session ${id}?`)) return; setBusy(true); setNotice(''); try { await router.deleteSession(id); if(selected?.id===id)setSelected(null); await load(); } catch(e:any) { setNotice(e?.message||'Unable to delete router session.'); } finally { setBusy(false); } };
  const test = async (id:string) => { setTesting(id); setNotice(''); try { const result=await router.testConnect(id); setNotice(result?.success===false ? (result?.error||result?.message||'Connection test failed.') : 'Connection test completed successfully.'); } catch(e:any) { setNotice(e?.message||'Connection test failed.'); } finally { setTesting(''); } };
  return <div className="stack"><div className="hero"><div><span className="eyebrow">ROUTER MANAGEMENT</span><h3>Router Sessions</h3><p>Manage router connection profiles used by the control plane.</p></div><div className="panel-actions"><button className="button secondary" onClick={()=>void load()} disabled={busy}><RefreshCw size={15} className={busy?'spin':''}/> Refresh</button><button className="primary" onClick={()=>openEditor()} disabled={busy}><Plus size={15}/> Add Router</button></div></div>{notice&&<div className="error banner">{notice}</div>}
    <section className="panel"><div className="panel-head"><div><h3><Router size={15}/> Available Routers</h3><span>{filtered.length} of {rows.length} sessions</span></div><span className="badge">{busy?'WORKING':'LIVE'}</span></div><div className="table-controls"><div className="table-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search router, IP, port, ID..."/></div></div><div className="table-wrap"><table><thead><tr><th>Session</th><th>Name</th><th>IP</th><th>Port</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((row,i)=>{const id=String(row.id||`row-${i}`); const status=row.status||(row.connected===true?'Connected':'Configured'); return <tr key={id}><td><b>{id}</b></td><td>{row.name||'—'}</td><td>{row.ip||'—'}</td><td>{row.port??'—'}</td><td>{status}</td><td><div className="inline-actions"><button className="icon tiny" title="Test" disabled={testing===id||busy} onClick={()=>void test(id)}>{testing===id?<RefreshCw size={14} className="spin"/>:<Check size={14}/>}</button><button className="icon tiny" title="Inspect" disabled={busy} onClick={()=>void inspect(row)}><Eye size={14}/></button><button className="icon tiny" title="Edit" disabled={busy} onClick={()=>openEditor(row)}><Pencil size={14}/></button><button className="icon tiny danger" title="Delete" disabled={busy} onClick={()=>void remove(id)}><Trash2 size={14}/></button></div></td></tr>;})}</tbody></table>{!filtered.length&&<div className="empty">No router sessions found.</div>}</div></section>
    {selected&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span className="eyebrow">ROUTER SESSION</span><h3>{selected.name||selected.id||'Session'}</h3></div><button className="icon" onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="detail-grid">{Object.entries(selected).map(([key,value])=><div className="metric" key={key}><span>{key}</span><b>{typeof value==='object'?JSON.stringify(value):String(value??'—')}</b></div>)}</div><div className="modal-actions"><button className="button secondary" onClick={()=>setSelected(null)}>Close</button></div></div></div>}
    {editor&&<div className="modal-backdrop"><div className="modal wide"><div className="modal-head"><div><span className="eyebrow">ROUTER SESSION</span><h3>{form.id?'Edit Router':'Add Router'}</h3></div><button className="icon" onClick={()=>setEditor(false)}><X size={18}/></button></div><div className="form-grid">{(['id','name','ip','port','user','password','hotspotName','dnsName','currency','reloadInterval','iface','idleTo','livereport'] as const).map(key=><label key={key}>{key}<input type={key==='password'?'password':'text'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} disabled={key==='id'&&false}/></label>)}</div><div className="modal-actions"><button className="button secondary" onClick={()=>setEditor(false)}>Cancel</button><button className="primary" onClick={()=>void save()} disabled={busy}>Save Router</button></div></div></div>}
  </div>;
}