import { useEffect, useMemo, useState } from 'react';
import { Check, Eye, Pencil, Plus, RefreshCw, Router, Search, Trash2, X } from 'lucide-react';
import { router } from '../api';

type Session = Record<string, any>;
type Form = { id:string; name:string; ip:string; port:string; user:string; password:string; hotspotName:string; dnsName:string; currency:string; reloadInterval:string; iface:string; idleTo:string; livereport:string };
const blank:Form={id:'',name:'',ip:'',port:'8728',user:'admin',password:'',hotspotName:'',dnsName:'',currency:'IDR',reloadInterval:'0',iface:'',idleTo:'0',livereport:''};
const asForm=(s:Session):Form=>({...blank,id:String(s.id||''),name:String(s.name||''),ip:String(s.ip||''),port:String(s.port??8728),user:String(s.user||''),hotspotName:String(s.hotspotName||''),dnsName:String(s.dnsName||''),currency:String(s.currency||'IDR'),reloadInterval:String(s.reloadInterval??0),iface:String(s.iface||''),idleTo:String(s.idleTo??0),livereport:String(s.livereport||'')});
export default function RouterSessionsPage(){const[rows,setRows]=useState<Session[]>([]);const[query,setQuery]=useState('');const[selected,setSelected]=useState<Session|null>(null);const[editor,setEditor]=useState(false);const[form,setForm]=useState<Form>(blank);const[busy,setBusy]=useState(false);const[testing,setTesting]=useState('');const[notice,setNotice]=useState('');
const load=async()=>{setBusy(true);setNotice('');try{const data=await router.sessions();const list=Array.isArray(data)?data:data?.sessions;setRows(Array.isArray(list)?list:[]);}catch(e:any){setNotice(e?.message||'Unable to load router sessions.')}finally{setBusy(false)}};useEffect(()=>{void load()},[]);
const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?rows.filter(r=>Object.values(r).some(v=>String(v??'').toLowerCase().includes(q))):rows},[rows,query]);
const inspect=async(row:Session)=>{const id=String(row.id||'');if(!id)return;setBusy(true);try{setSelected(await router.getSession(id)||row)}catch{setSelected(row)}finally{setBusy(false)}};
const save=async()=>{if(!form.id||!form.name||!form.ip){setNotice('ID, name, dan IP wajib diisi.');return}setBusy(true);setNotice('');try{await router.saveSession({...form,port:Number(form.port)||0,reloadInterval:Number(form.reloadInterval)||0,idleTo:Number(form.idleTo)||0});setEditor(false);await load()}catch(e:any){setNotice(e?.message||'Unable to save router session.')}finally{setBusy(false)}};
const remove=async(id:string)=>{if(!window.confirm(`Delete router session ${id}?`))return;setBusy(true);setNotice('');try{await router.deleteSession(id);setSelected(null);await load()}catch(e:any){setNotice(e?.message||'Unable to delete router session.')}finally{setBusy(false)}};
const test=async(id:string)=>{setTesting(id);setNotice('');try{const r=await router.testConnect(id);setNotice(r?.success===false?(r?.error||r?.message||'Connection test failed.'):'Connection test completed successfully.')}catch(e:any){setNotice(e?.message||'Connection test failed.')}finally{setTesting('')}};
return <div className="stack"><div className="hero"><div><span className="eyebrow">ROUTER MANAGEMENT</span><h3>Router Sessions</h3><p>Manage router connection profiles used by the control plane.</p></div><div className="panel-actions"><button className="button secondary"onClick={()=>void load()}disabled={busy}><RefreshCw size={15}className={busy?'spin':''}/> Refresh</button><button className="primary"onClick={()=>{setForm(blank);setEditor(true);setSelected(null)}}disabled={busy}><Plus size={15}/> Add Router</button></div></div>{notice&&<div className="error banner">{notice}</div>}<section className="panel"><div className="panel-head"><div><h3><Router size={15}/> Available Routers</h3><span>{filtered.length} of {rows.length} sessions</span></div><span className="badge">{busy?'WORKING':'LIVE'}</span></div><div className="table-controls"><div className="table-search"><Search size={15}/><input value={query}onChange={e=>setQuery(e.target.value)}placeholder="Search router, IP, port, ID..."/></div></div><div className="table-wrap"><table><thead><tr><th>Session</th><th>Name</th><th>IP</th><th>Port</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((r,i)=>{const id=String(r.id||`row-${i}`);return <tr key={id}><td><b>{id}</b></td><td>{r.name||'—'}</td><td>{r.ip||'—'}</td><td>{r.port??'—'}</td><td>{r.status||(r.connected===true?'Connected':'Configured')}</td><td><div className="inline-actions"><button className="icon tiny"title="Test"disabled={busy||testing===id}onClick={()=>void test(id)}>{testing===id?<RefreshCw size={14}className="spin"/>:<Check size={14}/>}</button><button className="icon tiny"title="Inspect"disabled={busy}onClick={()=>void inspect(r)}><Eye size={14}/></button><button className="icon tiny"title="Edit"disabled={busy}onClick={()=>{setForm(asForm(r));setEditor(true)}}><Pencil size={14}/></button><button className="icon tiny danger"title="Delete"disabled={busy}onClick={()=>void remove(id)}><Trash2 size={14}/></button></div></td></tr>})}</tbody></table>{!filtered.length&&<div className="empty">No router sessions found.</div>}</div></section>
{selected&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span className="eyebrow">ROUTER SESSION</span><h3>{selected.name||selected.id||'Session'}</h3></div><button className="icon"onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="detail-grid">{Object.entries(selected).map(([k,v])=><div className="metric"key={k}><span>{k}</span><b>{typeof v==='object'?JSON.stringify(v):String(v??'—')}</b></div>)}</div></div></div>}
{editor&&<div className="modal-backdrop"><div className="modal wide"><div className="modal-head"><div><span className="eyebrow">ROUTER SESSION</span><h3>{form.id?'Edit Router':'Add Router'}</h3></div><button className="icon"onClick={()=>setEditor(false)}><X size={18}/></button></div><div className="form-grid">{(['id','name','ip','port','user','password','hotspotName','dnsName','currency','reloadInterval','iface','idleTo','livereport']as const).map(k=><label key={k}>{k}<input type={k==='password'?'password':'text'}value={form[k]}onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><div className="modal-actions"><button className="button secondary"onClick={()=>setEditor(false)}>Cancel</button><button className="primary"onClick={()=>void save()}disabled={busy}>Save Router</button></div></div></div>}</div>}
