import { useEffect, useMemo, useState } from "react";
import { Bot, History, Pencil, Plus, RefreshCw, Send, Trash2, Wifi, X } from "lucide-react";
import { request } from "../api";
import "../telegram-management-page.css";

type Config = Record<string, any>;
type FormState = { id?: string; name: string; token: string; chatId: string; sessionId: string; notifSale: boolean; notifDaily: boolean; dailyTime: string; botEnabled: boolean; allowedUsers: string; defaultProfile: string; welcomeMsg: string };
const emptyForm: FormState = { name: "", token: "", chatId: "", sessionId: "", notifSale: false, notifDaily: false, dailyTime: "23:59", botEnabled: true, allowedUsers: "", defaultProfile: "", welcomeMsg: "" };
const maskToken = (value: string) => !value ? "—" : value.length <= 10 ? "••••••••" : `${value.slice(0, 5)}••••••${value.slice(-4)}`;
const enabled = (cfg: Config) => cfg.botEnabled !== false && cfg.bot_enabled !== false;

export default function TelegramManagementPage() {
  const [configs, setConfigs] = useState<Config[]>([]);
  const [logs, setLogs] = useState<Config[]>([]);
  const [selected, setSelected] = useState<Config | null>(null);
  const [form, setForm] = useState<FormState>(emptyForm);
  const [message, setMessage] = useState("Test dari Mikhmon");
  const [broadcastBotId, setBroadcastBotId] = useState("");
  const [broadcastMessage, setBroadcastMessage] = useState("");
  const [query, setQuery] = useState("");
  const [busy, setBusy] = useState(false);
  const [testingId, setTestingId] = useState<string | null>(null);
  const [broadcasting, setBroadcasting] = useState(false);
  const [notice, setNotice] = useState("");

  const load = async () => { setBusy(true); setNotice(""); try { const [c, l] = await Promise.all([request("/api/telegram/config"), request("/api/telegram/logs")]); const next = Array.isArray(c) ? c : []; setConfigs(next); setLogs(Array.isArray(l) ? l : []); if (!broadcastBotId && next.length) setBroadcastBotId(String(next[0].id || "")); } catch (e: any) { setNotice(e?.message || "Gagal memuat konfigurasi Telegram."); } finally { setBusy(false); } };
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return q ? configs.filter((cfg) => Object.values(cfg).some((v) => String(v ?? "").toLowerCase().includes(q))) : configs; }, [configs, query]);
  const openNew = () => { setSelected({}); setForm({ ...emptyForm }); setNotice(""); };
  const openEdit = (cfg: Config) => { setSelected(cfg); setForm({ ...emptyForm, ...cfg, token: cfg.token || cfg.botToken || "", chatId: cfg.chatId ?? cfg.chat_id ?? "", sessionId: cfg.sessionId ?? cfg.session_id ?? "", notifSale: cfg.notifSale ?? cfg.notif_sale ?? false, notifDaily: cfg.notifDaily ?? cfg.notif_daily ?? false, dailyTime: cfg.dailyTime ?? cfg.daily_time ?? "23:59", botEnabled: cfg.botEnabled ?? cfg.bot_enabled ?? true, allowedUsers: Array.isArray(cfg.allowedUsers) ? cfg.allowedUsers.join(",") : cfg.allowed_users || "", defaultProfile: cfg.defaultProfile ?? cfg.default_profile ?? "", welcomeMsg: cfg.welcomeMsg ?? cfg.welcome_msg ?? "" }); setNotice(""); };
  const save = async () => { setBusy(true); setNotice(""); try { const body = { ...(form.id ? { id: form.id } : {}), name: form.name, token: form.token, chatId: form.chatId, sessionId: form.sessionId, notifSale: !!form.notifSale, notifDaily: !!form.notifDaily, dailyTime: form.dailyTime, botEnabled: !!form.botEnabled, allowedUsers: form.allowedUsers.split(",").map((x) => x.trim()).filter(Boolean), defaultProfile: form.defaultProfile, welcomeMsg: form.welcomeMsg }; if (form.id) await request(`/api/telegram/config/${encodeURIComponent(form.id)}`, { method: "PUT", body: JSON.stringify(body) }); else await request("/api/telegram/config", { method: "POST", body: JSON.stringify(body) }); setSelected(null); await load(); } catch (e: any) { setNotice(e?.message || "Gagal menyimpan bot."); } finally { setBusy(false); } };
  const remove = async (id: string) => { if (!window.confirm("Hapus konfigurasi bot ini?")) return; setBusy(true); setNotice(""); try { await request(`/api/telegram/config/${encodeURIComponent(id)}`, { method: "DELETE" }); await load(); } catch (e: any) { setNotice(e?.message || "Gagal menghapus bot."); } finally { setBusy(false); } };
  const test = async (cfg: Config) => { const id = String(cfg.id || ""); setTestingId(id || "new"); setNotice(""); try { await request("/api/telegram/test", { method: "POST", body: JSON.stringify({ id, chatId: cfg.chatId || cfg.chat_id || "", message }) }); setNotice(`Test koneksi berhasil untuk ${cfg.name || id}.`); } catch (e: any) { setNotice(e?.message || "Test koneksi bot gagal."); } finally { setTestingId(null); } };
  const broadcast = async () => { if (!broadcastBotId || !broadcastMessage.trim()) { setNotice("Pilih bot dan isi pesan broadcast terlebih dahulu."); return; } if (!window.confirm("Kirim broadcast ke semua agen aktif yang memiliki Telegram ID?")) return; setBroadcasting(true); setNotice(""); try { const result = await request("/api/telegram/broadcast", { method: "POST", body: JSON.stringify({ id: broadcastBotId, message: broadcastMessage.trim() }) }); setNotice(result?.message || "Broadcast selesai."); setBroadcastMessage(""); } catch (e: any) { setNotice(e?.message || "Broadcast Telegram gagal."); } finally { setBroadcasting(false); } };

  return <div className="stack telegram-reference-page">
    <div className="tool-page-head"><span className="eyebrow">TELEGRAM BOT</span><h3>Telegram Bot Tools</h3><p>Kelola bot, uji koneksi, broadcast agen, dan pantau aktivitas bot.</p></div>
    {notice && <div className="error banner">{notice}</div>}
    <div className="telegram-reference-page compact-stat-row"><div className="compact-stat"><span>Total Bot</span><strong>{configs.length}</strong></div><div className="compact-stat"><span>Bot Aktif</span><strong>{configs.filter(enabled).length}</strong></div><div className="compact-stat"><span>Log Terakhir</span><strong>{logs.length}</strong></div></div>
    <div className="bot-tools-layout">
      <section className="reference-card reference-panel"><div className="reference-head"><div><h2>Daftar Bot Aktif</h2><div className="reference-sub">Konfigurasi bot Telegram yang tersedia.</div></div><div className="reference-action"><button className="button" disabled={busy || broadcasting} onClick={() => void load()}><RefreshCw size={14} className={busy ? "spin" : ""}/> Refresh</button><button className="button primary" disabled={busy || broadcasting} onClick={openNew}><Plus size={14}/> Tambah Bot</button></div></div><div className="reference-list">
        {configs.filter(enabled).map((cfg, i) => { const id = String(cfg.id ?? i); return <div className="bot-row" key={id}><div className="bot-main"><strong>Bot — {cfg.name || id}</strong><span>Admin ID: {cfg.chatId || cfg.chat_id || "—"}</span></div><div className="bot-actions"><span className="status-stopped">{enabled(cfg) ? "• STOPPED" : "• DISABLED"}</span><button className="icon tiny action-green" title="Test" onClick={() => void test(cfg)} disabled={testingId === id}><Wifi size={14}/></button><button className="icon tiny" title="Edit" onClick={() => openEdit(cfg)}><Pencil size={14}/></button><button className="icon tiny action-red" title="Hapus" onClick={() => void remove(id)} disabled={busy}><Trash2 size={14}/></button></div></div>; })}
        {!configs.filter(enabled).length && <div className="empty">Belum ada bot aktif.</div>}
      </div></section>
      <section className="reference-card reference-panel connection-panel"><div className="reference-head"><div><h2>Test Koneksi Bot</h2><div className="reference-sub">Verifikasi bahwa bot token valid dan dapat terhubung ke Telegram API.</div></div><Wifi size={17}/></div><div className="connection-copy">Pesan uji: <b>{message || "—"}</b></div><button className="primary" disabled={!configs.length || !!testingId} onClick={() => configs[0] && void test(configs[0])}><Send size={14}/> {testingId ? "Testing…" : "Test Koneksi"}</button></section>
    </div>
    <section className="reference-card broadcast-panel"><div className="reference-head"><div><h2>Broadcast ke Semua Agen</h2><div className="reference-sub">Kirim pesan ke semua user aktif di bot ini.</div></div><Send size={17}/></div><div className="detail-grid"><label className="metric"><span>Bot Pengirim</span><select value={broadcastBotId} onChange={(e) => setBroadcastBotId(e.target.value)} disabled={!configs.length || broadcasting}><option value="">Pilih bot...</option>{configs.map((cfg, i) => <option key={String(cfg.id ?? i)} value={String(cfg.id ?? "")}>{cfg.name || cfg.id || `Bot ${i + 1}`}</option>)}</select></label><label className="metric"><span>Pesan Broadcast</span><textarea rows={4} value={broadcastMessage} onChange={(e) => setBroadcastMessage(e.target.value)} placeholder="Tulis pesan broadcast..." disabled={broadcasting}/></label></div><div className="modal-actions"><button className="primary" disabled={broadcasting || !broadcastBotId || !broadcastMessage.trim()} onClick={() => void broadcast()}><Send size={14}/> {broadcasting ? "Mengirim…" : "Kirim Broadcast"}</button></div></section>
    <section className="reference-card log-panel"><div className="reference-head"><div><h2>Log Bot Terakhir</h2><div className="reference-sub">{logs.length} aktivitas terbaru</div></div><History size={17}/></div><div className="table-wrap"><table><thead><tr><th>Time</th><th>Event</th><th>Payload</th></tr></thead><tbody>{logs.slice(0, 100).map((log, i) => <tr key={String(log.id ?? i)}><td>{log.time || log.createdAt || "—"}</td><td>{log.event || log.type || log.status || "—"}</td><td className="mono">{JSON.stringify(log)}</td></tr>)}</tbody></table>{!logs.length && <div className="empty">Belum ada log bot.</div>}</div></section>
    {selected !== null && <div className="modal-backdrop"><div className="modal modal-wide"><div className="modal-head"><div><span className="eyebrow">TELEGRAM CONFIG</span><h3>{form.id ? "Edit Bot" : "Tambah Bot"}</h3></div><button className="icon" onClick={() => setSelected(null)}><X size={17}/></button></div><div className="detail-grid"><label className="metric"><span>Nama</span><input value={form.name} onChange={(e) => setForm({...form,name:e.target.value})}/></label><label className="metric"><span>Bot Token</span><input type="password" autoComplete="off" value={form.token} onChange={(e) => setForm({...form,token:e.target.value})}/></label><label className="metric"><span>Chat ID</span><input value={form.chatId} onChange={(e) => setForm({...form,chatId:e.target.value})}/></label><label className="metric"><span>Router Session</span><input value={form.sessionId} onChange={(e) => setForm({...form,sessionId:e.target.value})}/></label><label className="metric"><span>Default Profile</span><input value={form.defaultProfile} onChange={(e) => setForm({...form,defaultProfile:e.target.value})}/></label><label className="metric"><span>Daily Report Time</span><input type="time" value={form.dailyTime} onChange={(e) => setForm({...form,dailyTime:e.target.value})}/></label><label className="metric"><span>Bot Status</span><select value={String(form.botEnabled)} onChange={(e) => setForm({...form,botEnabled:e.target.value === "true"})}><option value="true">Enabled</option><option value="false">Disabled</option></select></label><label className="metric"><span>Sale Notification</span><select value={String(form.notifSale)} onChange={(e) => setForm({...form,notifSale:e.target.value === "true"})}><option value="true">Enabled</option><option value="false">Disabled</option></select></label><label className="metric"><span>Daily Notification</span><select value={String(form.notifDaily)} onChange={(e) => setForm({...form,notifDaily:e.target.value === "true"})}><option value="true">Enabled</option><option value="false">Disabled</option></select></label><label className="metric"><span>Allowed User IDs</span><input placeholder="123,456,789" value={form.allowedUsers} onChange={(e) => setForm({...form,allowedUsers:e.target.value})}/></label><label className="metric"><span>Welcome Message</span><textarea rows={4} value={form.welcomeMsg} onChange={(e) => setForm({...form,welcomeMsg:e.target.value})}/></label></div><div className="modal-actions"><button className="button secondary" onClick={() => setSelected(null)}>Batal</button><button className="primary" disabled={busy || !form.name || !form.token} onClick={() => void save()}>Simpan Bot</button></div></div></div>}
  </div>;
}
