# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import router_pb2 as router__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in router_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RouterServiceStub(object):
    """RouterService exposes MikroTik operations to other microservices
    (payment-service, erp-node-service, main-node-service) via gRPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TestConnect = channel.unary_unary(
                '/router.RouterService/TestConnect',
                request_serializer=router__pb2.TestConnectRequest.SerializeToString,
                response_deserializer=router__pb2.TestConnectResponse.FromString,
                _registered_method=True)
        self.GetDashboard = channel.unary_unary(
                '/router.RouterService/GetDashboard',
                request_serializer=router__pb2.GetDashboardRequest.SerializeToString,
                response_deserializer=router__pb2.GetDashboardResponse.FromString,
                _registered_method=True)
        self.ListActiveHotspotUsers = channel.unary_unary(
                '/router.RouterService/ListActiveHotspotUsers',
                request_serializer=router__pb2.ListActiveRequest.SerializeToString,
                response_deserializer=router__pb2.ListActiveResponse.FromString,
                _registered_method=True)
        self.ListHotspotUsers = channel.unary_unary(
                '/router.RouterService/ListHotspotUsers',
                request_serializer=router__pb2.ListHotspotUsersRequest.SerializeToString,
                response_deserializer=router__pb2.ListHotspotUsersResponse.FromString,
                _registered_method=True)
        self.AddHotspotUser = channel.unary_unary(
                '/router.RouterService/AddHotspotUser',
                request_serializer=router__pb2.AddHotspotUserRequest.SerializeToString,
                response_deserializer=router__pb2.AddHotspotUserResponse.FromString,
                _registered_method=True)
        self.RemoveHotspotUser = channel.unary_unary(
                '/router.RouterService/RemoveHotspotUser',
                request_serializer=router__pb2.RemoveHotspotUserRequest.SerializeToString,
                response_deserializer=router__pb2.RemoveHotspotUserResponse.FromString,
                _registered_method=True)
        self.ListHotspotProfiles = channel.unary_unary(
                '/router.RouterService/ListHotspotProfiles',
                request_serializer=router__pb2.ListProfilesRequest.SerializeToString,
                response_deserializer=router__pb2.ListProfilesResponse.FromString,
                _registered_method=True)
        self.GetHotspotProfile = channel.unary_unary(
                '/router.RouterService/GetHotspotProfile',
                request_serializer=router__pb2.GetProfileRequest.SerializeToString,
                response_deserializer=router__pb2.GetProfileResponse.FromString,
                _registered_method=True)
        self.GetSystemResource = channel.unary_unary(
                '/router.RouterService/GetSystemResource',
                request_serializer=router__pb2.SystemResourceRequest.SerializeToString,
                response_deserializer=router__pb2.SystemResourceResponse.FromString,
                _registered_method=True)
        self.GetInterfaces = channel.unary_unary(
                '/router.RouterService/GetInterfaces',
                request_serializer=router__pb2.InterfacesRequest.SerializeToString,
                response_deserializer=router__pb2.InterfacesResponse.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/router.RouterService/ListSessions',
                request_serializer=router__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=router__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/router.RouterService/GetSession',
                request_serializer=router__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=router__pb2.GetSessionResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/router.RouterService/CreateSession',
                request_serializer=router__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=router__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.UpdateSession = channel.unary_unary(
                '/router.RouterService/UpdateSession',
                request_serializer=router__pb2.UpdateSessionRequest.SerializeToString,
                response_deserializer=router__pb2.UpdateSessionResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/router.RouterService/DeleteSession',
                request_serializer=router__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=router__pb2.DeleteSessionResponse.FromString,
                _registered_method=True)


class RouterServiceServicer(object):
    """RouterService exposes MikroTik operations to other microservices
    (payment-service, erp-node-service, main-node-service) via gRPC.
    """

    def TestConnect(self, request, context):
        """Connection test
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDashboard(self, request, context):
        """Dashboard
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActiveHotspotUsers(self, request, context):
        """Hotspot users
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHotspotUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddHotspotUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveHotspotUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHotspotProfiles(self, request, context):
        """Hotspot profiles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHotspotProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemResource(self, request, context):
        """System info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInterfaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Router session management (CRUD) — the router connection profiles
        (id, ip, credentials, hotspot/UI settings) that every other RPC above
        is dialed against via session_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TestConnect': grpc.unary_unary_rpc_method_handler(
                    servicer.TestConnect,
                    request_deserializer=router__pb2.TestConnectRequest.FromString,
                    response_serializer=router__pb2.TestConnectResponse.SerializeToString,
            ),
            'GetDashboard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDashboard,
                    request_deserializer=router__pb2.GetDashboardRequest.FromString,
                    response_serializer=router__pb2.GetDashboardResponse.SerializeToString,
            ),
            'ListActiveHotspotUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActiveHotspotUsers,
                    request_deserializer=router__pb2.ListActiveRequest.FromString,
                    response_serializer=router__pb2.ListActiveResponse.SerializeToString,
            ),
            'ListHotspotUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHotspotUsers,
                    request_deserializer=router__pb2.ListHotspotUsersRequest.FromString,
                    response_serializer=router__pb2.ListHotspotUsersResponse.SerializeToString,
            ),
            'AddHotspotUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddHotspotUser,
                    request_deserializer=router__pb2.AddHotspotUserRequest.FromString,
                    response_serializer=router__pb2.AddHotspotUserResponse.SerializeToString,
            ),
            'RemoveHotspotUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveHotspotUser,
                    request_deserializer=router__pb2.RemoveHotspotUserRequest.FromString,
                    response_serializer=router__pb2.RemoveHotspotUserResponse.SerializeToString,
            ),
            'ListHotspotProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHotspotProfiles,
                    request_deserializer=router__pb2.ListProfilesRequest.FromString,
                    response_serializer=router__pb2.ListProfilesResponse.SerializeToString,
            ),
            'GetHotspotProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHotspotProfile,
                    request_deserializer=router__pb2.GetProfileRequest.FromString,
                    response_serializer=router__pb2.GetProfileResponse.SerializeToString,
            ),
            'GetSystemResource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemResource,
                    request_deserializer=router__pb2.SystemResourceRequest.FromString,
                    response_serializer=router__pb2.SystemResourceResponse.SerializeToString,
            ),
            'GetInterfaces': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInterfaces,
                    request_deserializer=router__pb2.InterfacesRequest.FromString,
                    response_serializer=router__pb2.InterfacesResponse.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=router__pb2.ListSessionsRequest.FromString,
                    response_serializer=router__pb2.ListSessionsResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=router__pb2.GetSessionRequest.FromString,
                    response_serializer=router__pb2.GetSessionResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=router__pb2.CreateSessionRequest.FromString,
                    response_serializer=router__pb2.CreateSessionResponse.SerializeToString,
            ),
            'UpdateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSession,
                    request_deserializer=router__pb2.UpdateSessionRequest.FromString,
                    response_serializer=router__pb2.UpdateSessionResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=router__pb2.DeleteSessionRequest.FromString,
                    response_serializer=router__pb2.DeleteSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'router.RouterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('router.RouterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RouterService(object):
    """RouterService exposes MikroTik operations to other microservices
    (payment-service, erp-node-service, main-node-service) via gRPC.
    """

    @staticmethod
    def TestConnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterService/TestConnect',
            router__pb2.TestConnectRequest.SerializeToString,
            router__pb2.TestConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDashboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterService/GetDashboard',
            router__pb2.GetDashboardRequest.SerializeToString,
            router__pb2.GetDashboardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActiveHotspotUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterService/ListActiveHotspotUsers',
            router__pb2.ListActiveRequest.SerializeToString,
            router__pb2.ListActiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHotspotUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterService/ListHotspotUsers',
            router__pb2.ListHotspotUsersRequest.SerializeToString,
            router__pb2.ListHotspotUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddHotspotUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterService/AddHotspotUser',
            router__pb2.AddHotspotUserRequest.SerializeToString,
            router__pb2.AddHotspotUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveHotspotUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterService/RemoveHotspotUser',
            router__pb2.RemoveHotspotUserRequest.SerializeToString,
            router__pb2.RemoveHotspotUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHotspotProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterService/ListHotspotProfiles',
            router__pb2.ListProfilesRequest.SerializeToString,
            router__pb2.ListProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHotspotProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterService/GetHotspotProfile',
            router__pb2.GetProfileRequest.SerializeToString,
            router__pb2.GetProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterService/GetSystemResource',
            router__pb2.SystemResourceRequest.SerializeToString,
            router__pb2.SystemResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInterfaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterService/GetInterfaces',
            router__pb2.InterfacesRequest.SerializeToString,
            router__pb2.InterfacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterService/ListSessions',
            router__pb2.ListSessionsRequest.SerializeToString,
            router__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterService/GetSession',
            router__pb2.GetSessionRequest.SerializeToString,
            router__pb2.GetSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterService/CreateSession',
            router__pb2.CreateSessionRequest.SerializeToString,
            router__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterService/UpdateSession',
            router__pb2.UpdateSessionRequest.SerializeToString,
            router__pb2.UpdateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterService/DeleteSession',
            router__pb2.DeleteSessionRequest.SerializeToString,
            router__pb2.DeleteSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
