import {useEffect,useMemo,useState} from 'react';
import {Activity,CircleGauge,Cpu,Database,LogOut,Menu,Network,RefreshCw,Router as RouterIcon,Search,Server,Users,X} from 'lucide-react';
import {auth,router} from './api';

type Session={id:string;name?:string;ip?:string;port?:number};
type Page='dashboard'|'hotspot-users'|'hotspot-profiles'|'pppoe-active'|'pppoe-profiles';
const nav:[string,Page,any][]=[['Overview','dashboard',CircleGauge],['Hotspot Users','hotspot-users',Users],['Hotspot Profiles','hotspot-profiles',Network],['PPPoE Active','pppoe-active',Activity],['PPPoE Profiles','pppoe-profiles',Server]];

export default function App(){
 const[me,setMe]=useState<any>();const[sessions,setSessions]=useState<Session[]>([]);const[session,setSession]=useState('');const[page,setPage]=useState<Page>('dashboard');const[open,setOpen]=useState(false);const[loading,setLoading]=useState(false);const[data,setData]=useState<any>();const[error,setError]=useState('');const[login,setLogin]=useState(false);const[credentials,setCredentials]=useState({username:'',password:''});
 const current=useMemo(()=>sessions.find(s=>s.id===session),[sessions,session]);const title=nav.find(n=>n[1]===page)?.[0]||'Overview';
 const load=async()=>{if(!session)return;setLoading(true);setError('');try{let r;if(page==='dashboard')r=await router.dashboard(session);if(page==='hotspot-users')r=await router.hotspotUsers(session,'all');if(page==='hotspot-profiles')r=await router.hotspotProfiles(session);if(page==='pppoe-active')r=await router.pppActive(session);if(page==='pppoe-profiles')r=await router.pppProfiles(session);setData(r)}catch(e:any){setError(e?.message==='UNAUTHORIZED'?'Session expired.':'Unable to load data.')}finally{setLoading(false)}};
 const boot=async()=>{try{const m=await auth.me();setMe(m);const r=await router.sessions();const rows=(r?.sessions??r??[]) as Session[];setSessions(rows);setSession(rows[0]?.id||'');setLogin(false)}catch{setLogin(true)}};
 useEffect(()=>{void boot()},[]);useEffect(()=>{if(!login)void load()},[page,session,login]);
 if(login)return <Login c={credentials} setC={setCredentials} error={error} onDone={boot}/>;
 return <div className="app-shell"><aside className={open?'sidebar open':'sidebar'}><Brand close={()=>setOpen(false)}/><div className="router-box"><span>ACTIVE ROUTER</span><select value={session} onChange={async e=>{setSession(e.target.value);await router.set(e.target.value)}}>{sessions.map(s=><option key={s.id} value={s.id}>{s.name||s.id}</option>)}</select><small>{current?.ip||'No address'}{current?.port?`:${current.port}`:''}</small></div><nav>{nav.map(([label,key,Icon])=><button key={key} className={page===key?'nav active':'nav'} onClick={()=>{setPage(key);setOpen(false)}}><Icon size={17}/>{label}</button>)}</nav><div className="sidebar-foot"><div className="user-mini"><div className="avatar">{String(me?.username||'A')[0].toUpperCase()}</div><div><b>{me?.username||'Admin'}</b><span>Administrator</span></div></div><button className="logout" onClick={async()=>{await auth.logout();setLogin(true)}}><LogOut size={16}/></button></div></aside><main><header><button className="icon mobile-only" onClick={()=>setOpen(true)}><Menu size={20}/></button><div><span className="eyebrow">NETWORK OPERATIONS</span><h2>{title}</h2></div><div className="top-actions"><div className="search"><Search size={16}/><input placeholder="Search..."/></div><button className="icon" onClick={()=>void load()}><RefreshCw size={17} className={loading?'spin':''}/></button></div></header><section className="content">{error&&<div className="error banner">{error}</div>}{page==='dashboard'?<Dashboard data={data} session={current}/>:<TablePage page={page} data={data} loading={loading}/>}</section></main></div>
}
function Brand({close}:{close:()=>void}){return <div className="brand"><div className="brand-mark"><RouterIcon size={18}/></div><div><b>NODEMON</b><span>NETWORK CONTROL</span></div><button className="icon mobile-only" onClick={close}><X size={18}/></button></div>}
function Login({c,setC,error,onDone}:any){return <div className="login"><div className="login-card"><Brand close={()=>{}}/><h1>Welcome back</h1><p>Sign in to manage routers and services.</p><form onSubmit={async e=>{e.preventDefault();try{await auth.login(c.username,c.password);await onDone()}catch{}}}><label>Username<input value={c.username} onChange={e=>setC({...c,username:e.target.value})}/></label><label>Password<input type="password" value={c.password} onChange={e=>setC({...c,password:e.target.value})}/></label>{error&&<div className="error">{error}</div>}<button className="primary">Sign in</button></form></div></div>}
function Dashboard({data,session}:any){const stats:any[]=[['Active Hotspot',data?.activeHotspotUsers??'—',Users],['Total Hotspot',data?.totalHotspotUsers??'—',Network],['CPU Load',data?.cpuLoad?`${data.cpuLoad}%`:'—',Cpu],['Free Memory',data?.freeMemory||'—',Database]];return <><div className="hero"><div><span className="eyebrow">LIVE ROUTER</span><h3>{session?.name||session?.id||'Router'}</h3><p>{session?.ip||'No address'} · RouterOS monitoring</p></div><div className="status"><i/>Connected</div></div><div className="stats">{stats.map(([label,value,Icon])=><div className="stat" key={label}><div className="stat-icon"><Icon size={18}/></div><div><span>{label}</span><strong>{value}</strong></div></div>)}</div><div className="panel"><div className="panel-head"><div><h3>System snapshot</h3><span>Current router telemetry</span></div><span className="badge">LIVE</span></div><div className="grid"><Metric n="RouterOS" v={data?.rosVersion||data?.version||'—'}/><Metric n="Uptime" v={data?.uptime||'—'}/><Metric n="Free HDD" v={data?.freeHdd||'—'}/><Metric n="Interfaces" v={data?.interfaces||'—'}/></div></div></>}
const Metric=({n,v}:any)=><div className="metric"><span>{n}</span><b>{String(v)}</b></div>;
function TablePage({page,data,loading}:any){const rows=data?.users||data?.profiles||data?.connections||data||[];if(!Array.isArray(rows))return <div className="panel empty">No data available.</div>;const cols=page==='hotspot-users'?['name','profile','comment','disabled']:page==='hotspot-profiles'?['name','rateLimit','sharedUsers','addressPool']:page==='pppoe-active'?['name','address','uptime','service']:['name','localAddress','remoteAddress','rateLimit','dns'];return <div className="panel"><div className="panel-head"><div><h3>{nav.find(n=>n[1]===page)?.[0]}</h3><span>{rows.length} records</span></div><span className="badge">{loading?'LOADING':'LIVE'}</span></div><div className="table-wrap"><table><thead><tr>{cols.map(c=><th key={c}>{c.replace(/([A-Z])/g,' $1')}</th>)}</tr></thead><tbody>{rows.map((r:any,i:number)=><tr key={r.id||i}>{cols.map(c=><td key={c}>{String(r[c]??'—')}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="empty">No records found.</div>}</div></div>}
